TASK2_TYPE_META = {
    "opinion": {"name": "Opinion", "emoji": "chat", "description": "Do you agree or disagree?"},
    "discussion": {"name": "Discussion", "emoji": "scale", "description": "Discuss both views"},
    "problem": {"name": "Problem/Solution", "emoji": "quiz", "description": "Causes and solutions"},
    "advantages": {"name": "Advantages", "emoji": "chart", "description": "Do benefits outweigh drawbacks?"},
    "double-question": {"name": "Double Question", "emoji": "puzzle", "description": "Answer two direct questions"},
}

TASK2_QUESTIONS = [
    {"id": 1, "type": "opinion", "title": "Online Education", "prompt": "Some people think online learning is better than classroom learning for university students. To what extent do you agree or disagree?"},
    {"id": 2, "type": "opinion", "title": "Private Cars", "prompt": "Governments should limit private car ownership to reduce congestion and pollution. To what extent do you agree or disagree?"},
    {"id": 3, "type": "opinion", "title": "Space Exploration", "prompt": "Money spent on space exploration should be redirected to solving problems on Earth. To what extent do you agree or disagree?"},
    {"id": 4, "type": "opinion", "title": "Homework", "prompt": "School children should not be given homework. To what extent do you agree or disagree?"},
    {"id": 5, "type": "opinion", "title": "Public Transport", "prompt": "Investing in public transport is the best way to solve urban traffic problems. To what extent do you agree or disagree?"},
    {"id": 6, "type": "discussion", "title": "University Purpose", "prompt": "Some people think universities should focus on job skills, while others think they should provide broad education. Discuss both views and give your opinion."},
    {"id": 7, "type": "discussion", "title": "Technology and Crime", "prompt": "Some believe technology reduces crime, while others think it creates new types of crime. Discuss both views and give your opinion."},
    {"id": 8, "type": "discussion", "title": "Global Culture", "prompt": "Globalisation leads to cultural loss according to some people, while others think it promotes understanding. Discuss both views and give your opinion."},
    {"id": 9, "type": "discussion", "title": "Advertising to Children", "prompt": "Some think advertising aimed at children should be banned, while others disagree. Discuss both views and give your opinion."},
    {"id": 10, "type": "problem", "title": "Urban Noise", "prompt": "Noise pollution in cities is increasing. What are the causes and what solutions can be proposed?"},
    {"id": 11, "type": "problem", "title": "Obesity", "prompt": "Obesity is rising among young people in many countries. What are the reasons and what solutions can governments and schools provide?"},
    {"id": 12, "type": "problem", "title": "Rural Population Decline", "prompt": "Many young adults are moving from rural areas to cities. What problems does this cause and what can be done?"},
    {"id": 13, "type": "advantages", "title": "Working from Home", "prompt": "More employees now work remotely. Do the advantages of this trend outweigh the disadvantages?"},
    {"id": 14, "type": "advantages", "title": "International Tourism", "prompt": "International tourism has expanded rapidly in recent decades. Do the advantages outweigh the disadvantages?"},
    {"id": 15, "type": "double-question", "title": "Reading Habits", "prompt": "People are reading fewer books today than in the past. Why is this happening? How can reading be encouraged?"},
]

LESSONS = [
    {"id": "t1-structure", "task": "task1", "section": "core", "icon": "structure", "title": "Task 1 Structure — the 4-paragraph formula", "subtitle": "Introduction · Overview · Body 1 · Body 2", "level": "Essential", "content": "Use a four-paragraph structure: paraphrased introduction, overview of key trends, and two body paragraphs with grouped comparisons and precise data."},
    {"id": "t1-intro", "task": "task1", "section": "core", "icon": "pen", "title": "How to write the Introduction", "subtitle": "Paraphrasing the prompt · what to avoid", "level": "Essential", "content": "Paraphrase the question with accurate vocabulary, keep it concise, and avoid opinions or extra details in Task 1 introductions."},
    {"id": "t1-overview", "task": "task1", "section": "core", "icon": "eye", "title": "How to write the Overview", "subtitle": "The most important paragraph", "level": "Essential", "content": "Your overview should identify the biggest trends, highest/lowest values, or notable changes without too many numbers."},
    {"id": "t1-body", "task": "task1", "section": "core", "icon": "write", "title": "How to write the Body paragraphs", "subtitle": "Selecting data · grouping · comparisons", "level": "Essential", "content": "Group related data points and compare them directly. Use figures to support every key statement."},
    {"id": "t1-qtypes", "task": "task1", "section": "qtypes", "icon": "chart", "title": "Bar charts and line graphs", "subtitle": "Trends · comparisons · time periods", "level": "Standard", "content": "Focus on trend verbs, proportional comparison language, and period-by-period changes."},
    {"id": "t1-pie-table", "task": "task1", "section": "qtypes", "icon": "pie", "title": "Pie charts and tables", "subtitle": "Proportions · selecting key data", "level": "Standard", "content": "Prioritise dominant segments and significant contrasts. Avoid listing all numbers mechanically."},
    {"id": "t1-process", "task": "task1", "section": "qtypes", "icon": "process", "title": "Process diagrams", "subtitle": "Sequencing and passive voice", "level": "Standard", "content": "Use sequencing words and passive structures where the actor is unknown or unimportant."},
    {"id": "t1-map", "task": "task1", "section": "qtypes", "icon": "map", "title": "Maps", "subtitle": "Location and change over time", "level": "Standard", "content": "Highlight major transformations and preserve clear spatial references with location phrases."},
    {"id": "t2-structure", "task": "task2", "section": "core", "icon": "structure", "title": "Task 2 Essay Structure", "subtitle": "Introduction · Body 1 · Body 2 · Conclusion", "level": "Essential", "content": "Present a clear thesis, build one central idea per body paragraph, and end with a concise conclusion."},
    {"id": "t2-intro", "task": "task2", "section": "core", "icon": "pen", "title": "How to write the Introduction", "subtitle": "Paraphrase + clear position", "level": "Essential", "content": "Paraphrase the task and state your position directly in one clear thesis sentence."},
    {"id": "t2-teel", "task": "task2", "section": "core", "icon": "write", "title": "How to write Body paragraphs — TEEL", "subtitle": "Topic sentence · explanation · example · link", "level": "Essential", "content": "Use a strong topic sentence, then explain, support with examples, and link back to the thesis."},
    {"id": "t2-conclusion", "task": "task2", "section": "core", "icon": "check", "title": "How to write the Conclusion", "subtitle": "Summarise and restate position", "level": "Essential", "content": "Summarise your key points briefly and restate your opinion without introducing new arguments."},
]

SKILLS = [
    {"id": "trend-vocabulary", "category": "vocabulary", "title": "Trend vocabulary", "desc": "rose · fell · surged · plateaued · doubled"},
    {"id": "reporting-verbs", "category": "vocabulary", "title": "Reporting verbs", "desc": "illustrates · reveals · indicates · demonstrates"},
    {"id": "proportion-vocabulary", "category": "vocabulary", "title": "Proportion vocabulary", "desc": "the majority of · accounted for · dominated"},
    {"id": "accurate-data-language", "category": "vocabulary", "title": "Accurate language for data", "desc": "approximately · roughly · just under"},
    {"id": "comparison-language", "category": "vocabulary", "title": "Comparison language", "desc": "whereas · by contrast · in comparison"},
    {"id": "opinion-language", "category": "vocabulary", "title": "Opinion language", "desc": "I firmly believe · compelling evidence", "new": True},
    {"id": "concession-language", "category": "vocabulary", "title": "Concession language", "desc": "Although · While it is true that", "new": True},
    {"id": "cause-effect-language", "category": "vocabulary", "title": "Cause and effect language", "desc": "has led to · as a consequence", "new": True},
    {"id": "hedging-language", "category": "vocabulary", "title": "Hedging language", "desc": "it could be argued · suggests that", "new": True},
    {"id": "example-language", "category": "vocabulary", "title": "Example language", "desc": "for instance · a case in point", "new": True},
    {"id": "informal-formal", "category": "word-strength", "title": "Informal → Formal language", "desc": '"a lot of" → "a significant number of"'},
    {"id": "participle-clauses", "category": "grammar", "title": "Participle clauses", "desc": "rose slightly, reaching 71%"},
    {"id": "passive-voice", "category": "grammar", "title": "Passive voice for Task 1", "desc": "Water is filtered · bottles are sorted"},
    {"id": "relative-clauses", "category": "grammar", "title": "Relative clauses", "desc": "which nearly doubled"},
    {"id": "topic-sentences", "category": "coherence", "title": "How to write a topic sentence", "desc": "First sentence of each body paragraph"},
    {"id": "paragraph-unity", "category": "coherence", "title": "Paragraph unity — one idea per paragraph", "desc": "Keep each paragraph focused"},
    {"id": "referencing-substitution", "category": "coherence", "title": "Referencing and substitution", "desc": "this / these / such / the former"},
    {"id": "academic-phrases", "category": "phrases", "title": "Academic phrases for Task 1", "desc": "It is noteworthy that · A striking feature is"},
    {"id": "overview-frames", "category": "phrases", "title": "Overview sentence frames", "desc": "Templates for any chart type"},
    {"id": "introduction-frames", "category": "phrases", "title": "Introduction frames", "desc": "Paraphrase openings for Task 1/2"},
    {"id": "linking-words", "category": "phrases", "title": "Linking words and connectives", "desc": "In contrast · Furthermore · Nevertheless"},
    {"id": "sequencing-language", "category": "phrases", "title": "Sequencing language — process diagrams", "desc": "Initially · Subsequently"},
    {"id": "paraphrasing", "category": "paraphrasing", "title": "How to paraphrase a question prompt", "desc": "Synonyms · structure changes"},
    {"id": "intro-correction", "category": "practice", "title": "Introduction paragraph: correcting errors", "desc": "Find and fix mistakes in 5 introductions"},
    {"id": "bar-gap-fill", "category": "practice", "title": "Bar chart: vocabulary gap fill", "desc": "Choose the correct trend word"},
    {"id": "line-vocab-ex", "category": "practice", "title": "Line graph: vocabulary exercise", "desc": "Select the right word for each trend"},
    {"id": "intro-rewrite", "category": "practice", "title": "Improving introductions — rewriting", "desc": "Rewrite weak introductions to Band 7"},
    {"id": "task2-intro-rewrite", "category": "practice", "title": "Task 2 introduction: rewriting exercise", "desc": "Rewrite 5 weak Task 2 intros", "new": True},
    {"id": "task2-body-gap", "category": "practice", "title": "Task 2 body paragraph: gap fill", "desc": "Choose the correct academic word", "new": True},
    {"id": "task2-conclusion-correction", "category": "practice", "title": "Task 2 conclusion: error correction", "desc": "Find and fix errors in 5 conclusions", "new": True},
    {"id": "task2-paraphrase-rewrite", "category": "practice", "title": "Paraphrasing exercise — rewrite 5 prompts", "desc": "Rewrite real IELTS prompts", "new": True},
    {"id": "informal-formal-rewrite", "category": "practice", "title": "Informal → formal: sentence rewriting", "desc": "Rewrite 8 informal sentences", "new": True},
]

SKILL_MAP = {
    "lexical_resource": ["trend-vocabulary", "reporting-verbs", "informal-formal"],
    "grammar_accuracy": ["participle-clauses", "passive-voice", "concession-language"],
    "coherence_cohesion": ["linking-words", "topic-sentences", "academic-phrases"],
    "task_achievement": ["overview-frames", "paraphrasing", "introduction-frames"],
    "task_response": ["opinion-language", "paraphrasing", "topic-sentences"],
}

