# Generated by Django 4.2.11 on 2026-05-26 05:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TestSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('listening', 'Listening'), ('reading', 'Reading'), ('writing', 'Writing'), ('speaking', 'Speaking'), ('full', 'Full IELTS Test')], db_index=True, max_length=16)),
                ('status', models.CharField(choices=[('in_progress', 'In progress'), ('completed', 'Completed')], default='in_progress', max_length=16)),
                ('band_overall', models.FloatField(blank=True, null=True)),
                ('band_listening', models.FloatField(blank=True, null=True)),
                ('band_reading', models.FloatField(blank=True, null=True)),
                ('band_writing', models.FloatField(blank=True, null=True)),
                ('band_speaking', models.FloatField(blank=True, null=True)),
                ('raw', models.JSONField(blank=True, default=dict)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='practice_test_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='SpeakingResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part', models.PositiveSmallIntegerField(choices=[(1, 'Part 1'), (2, 'Part 2'), (3, 'Part 3')])),
                ('question_index', models.PositiveSmallIntegerField()),
                ('question_text', models.TextField()),
                ('audio', models.FileField(blank=True, null=True, upload_to='speaking_audio/')),
                ('transcript', models.TextField(blank=True)),
                ('duration_seconds', models.FloatField(default=0)),
                ('fluency', models.FloatField(blank=True, null=True)),
                ('vocabulary', models.FloatField(blank=True, null=True)),
                ('grammar', models.FloatField(blank=True, null=True)),
                ('pronunciation', models.FloatField(blank=True, null=True)),
                ('band', models.FloatField(blank=True, null=True)),
                ('feedback', models.TextField(blank=True)),
                ('raw', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='speaking_responses', to='practice_test.testsession')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='speaking_responses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['session_id', 'part', 'question_index', '-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='testsession',
            index=models.Index(fields=['user', '-started_at'], name='practice_te_user_id_f09efe_idx'),
        ),
        migrations.AddIndex(
            model_name='testsession',
            index=models.Index(fields=['user', 'kind'], name='practice_te_user_id_7bd979_idx'),
        ),
        migrations.AddIndex(
            model_name='speakingresponse',
            index=models.Index(fields=['session', 'part', 'question_index'], name='practice_te_session_a4660e_idx'),
        ),
    ]
