"""Listening — numbers, dates, and spelling drills (data-driven)."""

DETAIL_DRILLS = [
    {
        "id": "num-1",
        "type": "number",
        "label": "Number",
        "audio": "drill_num1.mp3",
        "spoken": "The total cost comes to two hundred and forty-five pounds.",
        "answer": "245",
        "accepted": ["245", "£245", "245 pounds"],
        "hint": "Listen for hundreds — write digits only unless asked otherwise.",
    },
    {
        "id": "num-2",
        "type": "number",
        "label": "Number",
        "audio": "drill_num2.mp3",
        "spoken": "We expect around three point seven million visitors this year.",
        "answer": "3.7 million",
        "accepted": ["3.7 million", "3.7m", "3700000"],
        "hint": "Million follows the decimal figure.",
    },
    {
        "id": "date-1",
        "type": "date",
        "label": "Date",
        "audio": "drill_date1.mp3",
        "spoken": "The deadline is the fifteenth of March, twenty twenty-six.",
        "answer": "15 March 2026",
        "accepted": ["15 march 2026", "15/03/2026", "15th march 2026", "march 15 2026"],
        "hint": "IELTS often wants day before month for British English.",
    },
    {
        "id": "date-2",
        "type": "date",
        "label": "Date",
        "audio": "drill_date2.mp3",
        "spoken": "Classes resume on Monday the third of September.",
        "answer": "3 September",
        "accepted": ["3 september", "3rd september", "september 3"],
        "hint": "The day is the third — Monday is extra detail.",
    },
    {
        "id": "spell-1",
        "type": "spelling",
        "label": "Spelling",
        "audio": "drill_spell1.mp3",
        "spoken": "Her surname is spelled C-L-A-R-K-E.",
        "answer": "Clarke",
        "accepted": ["clarke"],
        "hint": "Write the name exactly as spelled out.",
    },
    {
        "id": "spell-2",
        "type": "spelling",
        "label": "Spelling",
        "audio": "drill_spell2.mp3",
        "spoken": "The reference is A-L-seven-four-two-nine.",
        "answer": "AL7429",
        "accepted": ["al7429"],
        "hint": "Letters and numbers with no spaces.",
    },
    {
        "id": "num-3",
        "type": "number",
        "label": "Number",
        "audio": "drill_num3.mp3",
        "spoken": "Room fourteen B, that's one four B.",
        "answer": "14B",
        "accepted": ["14b", "14 b", "fourteen b"],
        "hint": "Combine number and letter as written on forms.",
    },
    {
        "id": "date-3",
        "type": "date",
        "label": "Date",
        "audio": "drill_date3.mp3",
        "spoken": "The exam is on the twenty-second of June at nine fifteen.",
        "answer": "22 June",
        "accepted": ["22 june", "june 22", "22/06"],
        "hint": "Time (9:15) is separate — answer the date only if asked.",
    },
]

DRILL_TYPE_LABELS = {
    "number": "Numbers",
    "date": "Dates",
    "spelling": "Spelling",
}
