# Generated by Django 5.2.12 on 2026-04-04 04:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WritingPrompt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('topic', models.CharField(choices=[('environment', 'Environment'), ('health', 'Health'), ('technology', 'Technology'), ('education', 'Education'), ('society', 'Society')], max_length=32)),
                ('level', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3')])),
                ('instructions', models.TextField(help_text='What the learner should write (task, context, bullet points if needed).')),
                ('suggested_min_words', models.PositiveIntegerField(blank=True, help_text='Optional hint, e.g. 150 for a short paragraph task.', null=True)),
            ],
            options={
                'ordering': ['topic', 'level', 'title'],
            },
        ),
        migrations.CreateModel(
            name='WritingSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('prompt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='writing.writingprompt')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='writing_submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
