# Generated by Django 4.2.11 on 2026-04-16 05:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Essay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_type', models.CharField(choices=[('1', 'Task 1'), ('2', 'Task 2')], max_length=1)),
                ('question', models.TextField()),
                ('essay_text', models.TextField()),
                ('word_count', models.IntegerField(default=0)),
                ('band_score', models.FloatField(blank=True, null=True)),
                ('feedback_json', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
