# Generated by Django 5.2.12 on 2026-04-04 21:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('writing', '0002_ielts_writing'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='essay',
            name='coaching_journey',
            field=models.JSONField(blank=True, default=dict, help_text='AI coaching JSON per round (round1, round2, round3).'),
        ),
        migrations.AddField(
            model_name='essay',
            name='draft_1',
            field=models.TextField(blank=True, help_text='First attempt (coaching flow).'),
        ),
        migrations.AddField(
            model_name='essay',
            name='draft_2',
            field=models.TextField(blank=True, help_text='Second attempt (coaching flow).'),
        ),
        migrations.AlterField(
            model_name='essay',
            name='question',
            field=models.TextField(help_text='Snapshot of the prompt at submission time.'),
        ),
        migrations.AlterField(
            model_name='essay',
            name='student_answer',
            field=models.TextField(help_text='Final submitted text (draft 3 in coaching flow).'),
        ),
        migrations.CreateModel(
            name='ParaphrasePractice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.PositiveSmallIntegerField()),
                ('input_text', models.TextField()),
                ('feedback', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paraphrase_practices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WritingCoachingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('draft_1', models.TextField(blank=True)),
                ('draft_2', models.TextField(blank=True)),
                ('round_1_feedback', models.JSONField(default=dict)),
                ('round_2_feedback', models.JSONField(default=dict)),
                ('stage', models.PositiveSmallIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='writing_coaching_sessions', to=settings.AUTH_USER_MODEL)),
                ('writing_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coaching_sessions', to='writing.writingquestion')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
    ]
