# Generated by Django 5.2.12 on 2026-04-04 21:48

from django.db import migrations, models


def backfill_prompt_kinds(apps, schema_editor) -> None:
    WritingQuestion = apps.get_model("writing", "WritingQuestion")
    for q in WritingQuestion.objects.all():
        t = (q.question_text or "").lower()
        if q.question_type == "task1":
            if "map" in t:
                kind = "t1_map"
            elif "table" in t:
                kind = "t1_table"
            elif "diagram" in t or "process" in t or "stages" in t:
                kind = "t1_process"
            else:
                kind = "t1_chart"
        else:
            if "advantages" in t or "disadvantages" in t:
                kind = "t2_advantages"
            elif "problem" in t or "solution" in t or "measure" in t:
                kind = "t2_problem"
            elif "discuss both" in t or ("discuss" in t and "view" in t):
                kind = "t2_discussion"
            elif "why" in t and "?" in t and "do you think" not in t:
                kind = "t2_two_part"
            else:
                kind = "t2_opinion"
        q.prompt_kind = kind
        q.save(update_fields=["prompt_kind"])


class Migration(migrations.Migration):

    dependencies = [
        ('writing', '0003_coaching_paraphrase_essay_drafts'),
    ]

    operations = [
        migrations.AddField(
            model_name='paraphrasepractice',
            name='source_text',
            field=models.TextField(blank=True, help_text='AI-generated text the student paraphrased.'),
        ),
        migrations.AddField(
            model_name='paraphrasepractice',
            name='topic',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='writingquestion',
            name='prompt_kind',
            field=models.CharField(blank=True, choices=[('', 'Any style'), ('t1_chart', 'Task 1 · Charts & graphs'), ('t1_table', 'Task 1 · Tables'), ('t1_process', 'Task 1 · Process / diagram'), ('t1_map', 'Task 1 · Maps'), ('t2_opinion', 'Task 2 · Opinion / agree–disagree'), ('t2_discussion', 'Task 2 · Discussion (both views)'), ('t2_problem', 'Task 2 · Problem & solution'), ('t2_advantages', 'Task 2 · Advantages & disadvantages'), ('t2_two_part', 'Task 2 · Two-part questions')], default='', help_text='IELTS prompt style; empty = any (legacy).', max_length=16),
        ),
        migrations.AlterField(
            model_name='paraphrasepractice',
            name='input_text',
            field=models.TextField(help_text='Student paraphrase.'),
        ),
        migrations.RunPython(backfill_prompt_kinds, migrations.RunPython.noop),
    ]
