# Generated by Django 5.2.12 on 2026-04-04 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('writing', '0004_prompt_kind_paraphrase_topic'),
    ]

    operations = [
        migrations.AddField(
            model_name='essay',
            name='feedback_highlights',
            field=models.JSONField(blank=True, default=dict, help_text='issue_spans / strength_spans for highlighted final text display.'),
        ),
    ]
