# Generated by Django 5.2.12 on 2026-04-13 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boostingscore', '0002_userprofile_review_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='best_streak',
            field=models.PositiveIntegerField(default=0, help_text='Longest streak achieved.'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='reading_speed_wpm',
            field=models.PositiveIntegerField(blank=True, help_text='Last measured reading speed (words per minute), e.g. from skills lesson.', null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='streak',
            field=models.PositiveIntegerField(default=0, help_text='Current consecutive days with study activity (reading/vocab/writing).'),
        ),
    ]
