"""Gap-fill listening practice sets - IELTS Listening Section 1 style."""

_TEST_1 = {
    "test_number": 1,
    "id": "gap-test-1",
    "title": "Hotel conference booking",
    "audio": "gap_test1.mp3",
    "instructions": "Questions 1-5. Complete the notes. Write ONE WORD AND/OR A NUMBER for each answer.",
    "lines": [
        ("NARRATOR", "Section One. You will hear a conversation between a conference organiser and a hotel bookings clerk. Complete questions 1 to 5."),
        ("W", "Good morning, Harbour View Hotel. Reservations, Anna speaking."),
        ("M", "Hello Anna. I need to confirm rooms for our training conference."),
        ("W", "Certainly. How many delegates should I list?"),
        ("M", "It was 36 originally, but two more joined, so make that 38."),
        ("W", "Fine. Arrival date is the 14th of September?"),
        ("M", "No, that changed. They arrive on the 15th, and check out two days later."),
        ("W", "Noted. Any preference for room type?"),
        ("M", "We thought about twins, but everyone asked for single rooms in the end."),
        ("W", "Single rooms at the conference rate are 105 pounds per night."),
        ("M", "I wrote down 95 from an old quote."),
        ("W", "Ninety-five was winter pricing. The final rate now is 105."),
        ("W", "Do you need parking spaces as well?"),
        ("M", "Yes, please book one space for our minibus, not two."),
        ("W", "All right. I will email confirmation this afternoon."),
    ],
    "questions": [
        {"id": "q1", "render": "text", "text": "Total number of attendees: ______", "answer": ["38"], "explanation": "The caller updates the figure from 36 to the final total of 38."},
        {"id": "q2", "render": "text", "text": "Date delegates arrive: 15 ______", "answer": ["september"], "explanation": "14th is corrected; the final arrival month is September."},
        {"id": "q3", "render": "text", "text": "Confirmed room category: ______", "answer": ["single"], "explanation": "Twin rooms are considered but the final choice is single rooms."},
        {"id": "q4", "render": "text", "text": "Agreed nightly room price: ______", "answer": ["105"], "explanation": "95 is an outdated price; the final agreed rate is 105."},
        {"id": "q5", "render": "text", "text": "Parking spaces required for conference vehicle: ______", "answer": ["1"], "explanation": "They settle on one parking space, not two."},
    ],
}

_TEST_2 = {
    "test_number": 2,
    "id": "gap-test-2",
    "title": "Language course enrolment",
    "audio": "gap_test2.mp3",
    "instructions": "Questions 1-5. Complete the notes. Write ONE WORD AND/OR A NUMBER for each answer.",
    "lines": [
        ("NARRATOR", "Section One. You will hear a student enrolling in an evening language course. Complete questions 1 to 5."),
        ("W2", "Central Language Institute, enrolment desk."),
        ("M", "Hi, I want to sign up for French classes."),
        ("W2", "Of course. Which level do you need?"),
        ("M", "I first selected beginner, but my teacher advised intermediate."),
        ("W2", "Intermediate, fine. Which class day suits you?"),
        ("M", "I can no longer do Monday, so please place me in the Wednesday group."),
        ("W2", "That class starts at 6:30 p.m."),
        ("M", "I thought it started at 6:15."),
        ("W2", "Six fifteen was last term. The new start time is 6:30."),
        ("W2", "The course fee is 240 pounds for ten weeks."),
        ("M", "I saw 260 on a leaflet."),
        ("W2", "That leaflet is old. The current fee is 240."),
        ("W2", "Can I also take your emergency contact surname?"),
        ("M", "Use Patel - sorry, that is my old record. It should be Shah."),
        ("W2", "Great, I have updated that."),
    ],
    "questions": [
        {"id": "q1", "render": "text", "text": "Chosen study level: ______", "answer": ["intermediate"], "explanation": "Beginner is mentioned first, then changed to intermediate."},
        {"id": "q2", "render": "text", "text": "Weekly class day: ______", "answer": ["wednesday"], "explanation": "Monday is rejected; Wednesday is confirmed."},
        {"id": "q3", "render": "text", "text": "Lesson begins at ______ p.m.", "answer": ["6:30"], "explanation": "6:15 is an old schedule; the final time is 6:30 p.m."},
        {"id": "q4", "render": "text", "text": "Ten-week fee: ______", "answer": ["240"], "explanation": "260 is from an old leaflet; the actual fee is 240."},
        {"id": "q5", "render": "text", "text": "Emergency contact family name: ______", "answer": ["shah"], "explanation": "Patel is corrected to Shah as the final surname."},
    ],
}

_TEST_3 = {
    "test_number": 3,
    "id": "gap-test-3",
    "title": "Car hire reservation",
    "audio": "gap_test3.mp3",
    "instructions": "Questions 1-5. Complete the notes. Write ONE WORD AND/OR A NUMBER for each answer.",
    "lines": [
        ("NARRATOR", "Section One. You will hear a customer booking a hire car. Complete questions 1 to 5."),
        ("M2", "QuickWheels Car Hire, Ryan speaking."),
        ("W", "Hello, I need to reserve a car for a short business trip."),
        ("M2", "No problem. Which branch will you collect from?"),
        ("W", "I first planned to use the airport office, but please change it to the station branch."),
        ("M2", "Done. Collection date?"),
        ("W", "Friday the 10th - sorry, I mean Saturday the 11th of July."),
        ("M2", "And your return day?"),
        ("W", "Not Monday now. I will return it on Tuesday."),
        ("M2", "Do you need a compact or SUV model?"),
        ("W", "Compact is fine."),
        ("M2", "With standard insurance, that is 62 pounds per day."),
        ("W", "I thought it would be 55."),
        ("M2", "Fifty-five is without cover. The final insured rate is 62."),
        ("M2", "Any extra equipment?"),
        ("W", "Yes, add a GPS. I do not need a child seat."),
    ],
    "questions": [
        {"id": "q1", "render": "text", "text": "Pick-up location selected: ______ branch", "answer": ["station"], "explanation": "Airport is mentioned first, but the final branch is station."},
        {"id": "q2", "render": "text", "text": "Collection month: ______", "answer": ["july"], "explanation": "The final corrected date given is in July."},
        {"id": "q3", "render": "text", "text": "Vehicle hand-back day: ______", "answer": ["tuesday"], "explanation": "Monday is changed to Tuesday."},
        {"id": "q4", "render": "text", "text": "Daily cost including insurance: ______", "answer": ["62"], "explanation": "55 is the uninsured price; insured daily price is 62."},
        {"id": "q5", "render": "text", "text": "Navigation extra requested: ______", "answer": ["gps"], "explanation": "The caller confirms GPS as the required extra."},
    ],
}

_TEST_4 = {
    "test_number": 4,
    "id": "gap-test-4",
    "title": "Community garden plot application",
    "audio": "gap_test4.mp3",
    "instructions": "Questions 1-5. Complete the notes. Write ONE WORD AND/OR A NUMBER for each answer.",
    "lines": [
        ("NARRATOR", "Section One. You will hear a caller applying for a community garden plot. Complete questions 1 to 5."),
        ("W2", "Riverside Community Garden office. How can I help?"),
        ("M", "Hi, I am applying for a plot this season."),
        ("W2", "Would you like a full or half plot?"),
        ("M", "I wanted a full one, but I can only manage a half plot."),
        ("W2", "Any preferred zone?"),
        ("M", "I wrote down Zone C."),
        ("W2", "Zone C is mostly shaded. Zone B gets better morning sun."),
        ("M", "Then please put me in Zone B."),
        ("W2", "Annual membership is 75 pounds plus a key deposit."),
        ("M", "Is the deposit still 10 pounds?"),
        ("W2", "No, it increased this year. It is now 15."),
        ("W2", "Training sessions are on the 4th and 11th of September."),
        ("M", "I cannot attend on the 4th, so book me for the 11th."),
        ("W2", "Final detail: what will you mostly grow?"),
        ("M", "Mostly vegetables - especially tomatoes."),
    ],
    "questions": [
        {"id": "q1", "render": "text", "text": "Requested plot size: ______", "answer": ["half"], "explanation": "The caller changes from full to half plot."},
        {"id": "q2", "render": "text", "text": "Preferred garden zone: ______", "answer": ["b"], "explanation": "Zone C is replaced with Zone B after advice."},
        {"id": "q3", "render": "text", "text": "Updated key deposit amount: ______", "answer": ["15"], "explanation": "10 is an old amount; new deposit is 15."},
        {"id": "q4", "render": "text", "text": "Orientation session date: 11 ______", "answer": ["september"], "explanation": "The final selected session is on the 11th of September."},
        {"id": "q5", "render": "text", "text": "Main produce category: ______", "answer": ["vegetables"], "explanation": "The applicant says they will focus mostly on vegetables."},
    ],
}

_TEST_5 = {
    "test_number": 5,
    "id": "gap-test-5",
    "title": "Festival volunteer registration",
    "audio": "gap_test5.mp3",
    "instructions": "Questions 1-5. Complete the notes. Write ONE WORD AND/OR A NUMBER for each answer.",
    "lines": [
        ("NARRATOR", "Section One. You will hear a volunteer applying to work at a festival. Complete questions 1 to 5."),
        ("M2", "Oakfield Festival volunteer team, Liam speaking."),
        ("W", "Hello, I would like to register as a volunteer this summer."),
        ("M2", "Great. Which team do you want: catering, ticketing, or camping support?"),
        ("W", "I did catering last year, so this time I want ticketing."),
        ("M2", "What date can you start?"),
        ("W", "I put the 7th on my form, but I can start earlier on the 6th of August."),
        ("M2", "Ticketing shifts are usually 6 hours."),
        ("W", "I heard they were 5."),
        ("M2", "Five was last year. This year they are 6 hours."),
        ("M2", "Each shift includes a meal voucher worth 9 pounds."),
        ("W", "Someone said 11 pounds."),
        ("M2", "No, finance approved 9 as the final value."),
        ("M2", "Where should we send your entry pass?"),
        ("W", "Use Flat 18 - sorry, that was my old address. It is Flat 28 now."),
        ("M2", "Thanks, I have updated your details."),
    ],
    "questions": [
        {"id": "q1", "render": "text", "text": "Selected volunteer team: ______", "answer": ["ticketing"], "explanation": "Catering is past experience; ticketing is the final choice."},
        {"id": "q2", "render": "text", "text": "Start month: ______", "answer": ["august"], "explanation": "The corrected start date is the 6th of August."},
        {"id": "q3", "render": "text", "text": "Length of one shift: ______", "answer": ["6"], "explanation": "Old information says 5, but final shift length is 6."},
        {"id": "q4", "render": "text", "text": "Meal voucher value: ______", "answer": ["9"], "explanation": "11 is rejected; confirmed voucher amount is 9."},
        {"id": "q5", "render": "text", "text": "Current flat number: ______", "answer": ["28"], "explanation": "Flat 18 is corrected to Flat 28."},
    ],
}

TESTS = [_TEST_1, _TEST_2, _TEST_3, _TEST_4, _TEST_5]
