"""Map / plan labelling practice sets (IELTS Section Two, Band 6-7+)."""

from listening.practice_sets.map_svgs import (
    CAMPUS_MAP_SVG,
    FARM_MAP_SVG,
    MAP_OPTIONS,
    MUSEUM_MAP_SVG,
    RIVERSIDE_PARK_MAP_SVG,
    SPORTS_CENTRE_MAP_SVG,
)

_TEST_1 = {
    "test_number": 1,
    "id": "map-test-1",
    "title": "Section Two: Riverside Park",
    "audio": "map_test1.mp3",
    "map_svg": RIVERSIDE_PARK_MAP_SVG,
    "instructions": "Questions 1-5. Label the map. Choose the correct letter, A-F, for each place.",
    "lines": [
        ("NARRATOR", "Section Two. You will hear part of a talk about Riverside Park."),
        ("W2", "As you enter from the south, the first building looks like the cafe at B, but that is the information point."),
        ("W2", "The cafe is actually in the south-west corner at A."),
        ("W2", "For visitor information, go to B in the centre beside the main path."),
        ("W2", "People often think toilets are at E near the play area, but they are at C on the west side path."),
        ("W2", "The playground itself is at E in the north-east open space."),
        ("W2", "Finally, boat hire is not near A. It is by the river at F."),
    ],
    "questions": [
        {
            "id": "q1",
            "render": "select",
            "text": "Cafe",
            "options": MAP_OPTIONS,
            "answer": "A",
            "explanation": "The speaker first mentions B as a trap, then corrects cafe to A.",
        },
        {
            "id": "q2",
            "render": "select",
            "text": "Information point",
            "options": MAP_OPTIONS,
            "answer": "B",
            "explanation": "The centre location is confirmed as B.",
        },
        {
            "id": "q3",
            "render": "select",
            "text": "Toilets",
            "options": MAP_OPTIONS,
            "answer": "C",
            "explanation": "E is the distractor; toilets are corrected to C.",
        },
        {
            "id": "q4",
            "render": "select",
            "text": "Playground",
            "options": MAP_OPTIONS,
            "answer": "E",
            "explanation": "The north-east play area is identified as E.",
        },
        {
            "id": "q5",
            "render": "select",
            "text": "Boat hire",
            "options": MAP_OPTIONS,
            "answer": "F",
            "explanation": "After rejecting A, the final location is F by the river.",
        },
    ],
}

_TEST_2 = {
    "test_number": 2,
    "id": "map-test-2",
    "title": "Section Two: Campus open day",
    "audio": "map_test2.mp3",
    "map_svg": CAMPUS_MAP_SVG,
    "instructions": "Questions 1-5. Label the map. Choose the correct letter, A-F, for each place.",
    "lines": [
        ("NARRATOR", "Section Two. You will hear part of an orientation talk on campus open day."),
        ("M2", "From the main gate, many visitors walk to B thinking that is the student union, but the union is A."),
        ("M2", "The library is at B in the upper-west area."),
        ("M2", "The science block sits in the upper centre at C."),
        ("M2", "Lunch is not served in A today; the main cafeteria is at E on the eastern side."),
        ("M2", "Registration was once in D, but for open day it has moved to F near the central crossing."),
    ],
    "questions": [
        {
            "id": "q1",
            "render": "select",
            "text": "Student union",
            "options": MAP_OPTIONS,
            "answer": "A",
            "explanation": "B is mentioned first as a distractor; union is corrected to A.",
        },
        {
            "id": "q2",
            "render": "select",
            "text": "Library",
            "options": MAP_OPTIONS,
            "answer": "B",
            "explanation": "The upper-west building is confirmed as B.",
        },
        {
            "id": "q3",
            "render": "select",
            "text": "Science block",
            "options": MAP_OPTIONS,
            "answer": "C",
            "explanation": "The science block is directly stated as C.",
        },
        {
            "id": "q4",
            "render": "select",
            "text": "Main cafeteria",
            "options": MAP_OPTIONS,
            "answer": "E",
            "explanation": "A is a trap; cafeteria location is E.",
        },
        {
            "id": "q5",
            "render": "select",
            "text": "Registration desk",
            "options": MAP_OPTIONS,
            "answer": "F",
            "explanation": "The speaker rejects D and updates registration to F.",
        },
    ],
}

_TEST_3 = {
    "test_number": 3,
    "id": "map-test-3",
    "title": "Section Two: Museum plan",
    "audio": "map_test3.mp3",
    "map_svg": MUSEUM_MAP_SVG,
    "instructions": "Questions 1-5. Label the map. Choose the correct letter, A-F, for each place.",
    "lines": [
        ("NARRATOR", "Section Two. You will hear part of a museum orientation talk."),
        ("W2", "When you enter, some visitors queue at B, but the ticket desk is actually A by the lower corridor."),
        ("W2", "The temporary exhibition room is B in the middle-left area."),
        ("W2", "Archaeology is not in D. It is in C at the top-left corner."),
        ("W2", "The museum shop is therefore D at the top centre."),
        ("W2", "Modern art is placed at E, while F is used for education workshops."),
    ],
    "questions": [
        {
            "id": "q1",
            "render": "select",
            "text": "Ticket desk",
            "options": MAP_OPTIONS,
            "answer": "A",
            "explanation": "B is a distractor; the final ticket desk location is A.",
        },
        {
            "id": "q2",
            "render": "select",
            "text": "Temporary exhibition",
            "options": MAP_OPTIONS,
            "answer": "B",
            "explanation": "The room is clearly identified as B.",
        },
        {
            "id": "q3",
            "render": "select",
            "text": "Archaeology gallery",
            "options": MAP_OPTIONS,
            "answer": "C",
            "explanation": "D is rejected first, then archaeology is corrected to C.",
        },
        {
            "id": "q4",
            "render": "select",
            "text": "Museum shop",
            "options": MAP_OPTIONS,
            "answer": "D",
            "explanation": "After archaeology is moved to C, the shop remains D.",
        },
        {
            "id": "q5",
            "render": "select",
            "text": "Modern art gallery",
            "options": MAP_OPTIONS,
            "answer": "E",
            "explanation": "E is modern art, while F is mentioned as a distractor.",
        },
    ],
}

_TEST_4 = {
    "test_number": 4,
    "id": "map-test-4",
    "title": "Section Two: Farm open day",
    "audio": "map_test4.mp3",
    "map_svg": FARM_MAP_SVG,
    "instructions": "Questions 1-5. Label the map. Choose the correct letter, A-F, for each place.",
    "lines": [
        ("NARRATOR", "Section Two. You will hear part of a farm open-day announcement."),
        ("M2", "From the car park, families often walk toward C, but the animal feeding area is at A."),
        ("M2", "The farm shop is in the top-left area at B, not near the rides."),
        ("M2", "The petting barn is at C, directly east of the shop."),
        ("M2", "You may expect machinery by F on the lower route, but the machinery display is D."),
        ("M2", "First aid is at E in the eastern building just below D."),
    ],
    "questions": [
        {
            "id": "q1",
            "render": "select",
            "text": "Animal feeding area",
            "options": MAP_OPTIONS,
            "answer": "A",
            "explanation": "C is used as a distractor before the correct location A.",
        },
        {
            "id": "q2",
            "render": "select",
            "text": "Farm shop",
            "options": MAP_OPTIONS,
            "answer": "B",
            "explanation": "The top-left building is confirmed as B.",
        },
        {
            "id": "q3",
            "render": "select",
            "text": "Petting barn",
            "options": MAP_OPTIONS,
            "answer": "C",
            "explanation": "The barn is positioned east of the shop at C.",
        },
        {
            "id": "q4",
            "render": "select",
            "text": "Machinery display",
            "options": MAP_OPTIONS,
            "answer": "D",
            "explanation": "F is rejected, and machinery is corrected to D.",
        },
        {
            "id": "q5",
            "render": "select",
            "text": "First aid point",
            "options": MAP_OPTIONS,
            "answer": "E",
            "explanation": "The speaker gives E as the final first-aid location.",
        },
    ],
}

_TEST_5 = {
    "test_number": 5,
    "id": "map-test-5",
    "title": "Section Two: Sports centre tour",
    "audio": "map_test5.mp3",
    "map_svg": SPORTS_CENTRE_MAP_SVG,
    "instructions": "Questions 1-5. Label the map. Choose the correct letter, A-F, for each place.",
    "lines": [
        ("NARRATOR", "Section Two. You will hear part of a guided tour of a sports centre."),
        ("W2", "After reception, many people turn to B first, but the fitness gym is actually A."),
        ("W2", "Changing rooms are at B above the gym on the western side."),
        ("W2", "The dance studio is not at D. It is at C in the upper-left central area."),
        ("W2", "Yoga is at D opposite the dance studio."),
        ("W2", "The climbing wall is at E in the east-middle section, while F is the sports hall."),
    ],
    "questions": [
        {
            "id": "q1",
            "render": "select",
            "text": "Fitness gym",
            "options": MAP_OPTIONS,
            "answer": "A",
            "explanation": "B is mentioned first to distract; gym is corrected to A.",
        },
        {
            "id": "q2",
            "render": "select",
            "text": "Changing rooms",
            "options": MAP_OPTIONS,
            "answer": "B",
            "explanation": "Changing rooms are confirmed at B.",
        },
        {
            "id": "q3",
            "render": "select",
            "text": "Dance studio",
            "options": MAP_OPTIONS,
            "answer": "C",
            "explanation": "D is rejected before the speaker confirms C.",
        },
        {
            "id": "q4",
            "render": "select",
            "text": "Yoga room",
            "options": MAP_OPTIONS,
            "answer": "D",
            "explanation": "Yoga is explicitly located at D.",
        },
        {
            "id": "q5",
            "render": "select",
            "text": "Climbing wall",
            "options": MAP_OPTIONS,
            "answer": "E",
            "explanation": "E is climbing wall; F is mentioned as a contrast.",
        },
    ],
}

TESTS = [_TEST_1, _TEST_2, _TEST_3, _TEST_4, _TEST_5]
