"""Matching practice sets (IELTS Section Three, Band 6-7+)."""

_TEST_1 = {
    "test_number": 1,
    "id": "matching-test-1",
    "title": "Section Three: Charity dinner planning",
    "audio": "matching_test1.mp3",
    "instructions": "Who will be responsible for each task? Choose A, B or C.",
    "lines": [
        ("NARRATOR", "Section Three. You will hear two volunteers discussing preparations for a charity dinner."),
        ("W", "Sam, I can order table decorations, unless you want to do that."),
        ("M", "You choose colours better, so decorations should stay with you."),
        ("W", "Fine. About contacting caterers, I started yesterday but only asked for prices."),
        ("M", "Then I will finish that and confirm the menu choices."),
        ("W", "Good. What about writing the sponsor thank-you cards?"),
        ("M", "Let's both sign those, because donors know us both."),
        ("W", "Agreed. For social media posters, you did great last year."),
        ("M", "I can design them again, while you prepare the guest list."),
    ],
    "questions": [
        {
            "id": "q1",
            "render": "select",
            "text": "Ordering table decorations",
            "options": ["A Hana", "B Sam", "C both of them"],
            "answer": "A Hana",
            "explanation": "Sam declines and says Hana should do decorations.",
        },
        {
            "id": "q2",
            "render": "select",
            "text": "Final contact with caterers",
            "options": ["A Hana", "B Sam", "C both of them"],
            "answer": "B Sam",
            "explanation": "Hana begins the task, but Sam takes final responsibility (trap).",
        },
        {
            "id": "q3",
            "render": "select",
            "text": "Writing sponsor thank-you cards",
            "options": ["A Hana", "B Sam", "C both of them"],
            "answer": "C both of them",
            "explanation": "They agree to sign the cards together.",
        },
        {
            "id": "q4",
            "render": "select",
            "text": "Designing social media posters",
            "options": ["A Hana", "B Sam", "C both of them"],
            "answer": "B Sam",
            "explanation": "Sam explicitly offers to design the posters.",
        },
        {
            "id": "q5",
            "render": "select",
            "text": "Preparing the guest list",
            "options": ["A Hana", "B Sam", "C both of them"],
            "answer": "A Hana",
            "explanation": "Sam handles posters while Hana prepares the guest list.",
        },
    ],
}

_TEST_2 = {
    "test_number": 2,
    "id": "matching-test-2",
    "title": "Section Three: Museum event preparation",
    "audio": "matching_test2.mp3",
    "instructions": "Who will be responsible for each task? Choose A, B or C.",
    "lines": [
        ("NARRATOR", "Section Three. You will hear two museum staff planning a special event."),
        ("W", "Leo, can you print the exhibition leaflets this afternoon?"),
        ("M", "I can start, but my printer access ends at noon. Better if you print them."),
        ("W", "All right, I will print them. You can still check the final design."),
        ("M", "Sure. I'll arrange delivery times with the sculpture transport company."),
        ("W", "Great. Do we both brief the volunteer guides?"),
        ("M", "Yes, that meeting needs both of us present."),
        ("W", "Then I will call the local radio station about promotion."),
        ("M", "Perfect, and I will set up the projector test in the main hall."),
    ],
    "questions": [
        {
            "id": "q1",
            "render": "select",
            "text": "Printing exhibition leaflets",
            "options": ["A Nadiya", "B Leo", "C both of them"],
            "answer": "A Nadiya",
            "explanation": "Leo starts as an option but responsibility shifts to Nadiya.",
        },
        {
            "id": "q2",
            "render": "select",
            "text": "Arranging sculpture transport",
            "options": ["A Nadiya", "B Leo", "C both of them"],
            "answer": "B Leo",
            "explanation": "Leo takes direct responsibility for transport timing.",
        },
        {
            "id": "q3",
            "render": "select",
            "text": "Briefing volunteer guides",
            "options": ["A Nadiya", "B Leo", "C both of them"],
            "answer": "C both of them",
            "explanation": "They decide the guide briefing requires both of them.",
        },
        {
            "id": "q4",
            "render": "select",
            "text": "Contacting local radio",
            "options": ["A Nadiya", "B Leo", "C both of them"],
            "answer": "A Nadiya",
            "explanation": "Nadiya says she will call the station.",
        },
        {
            "id": "q5",
            "render": "select",
            "text": "Testing the projector",
            "options": ["A Nadiya", "B Leo", "C both of them"],
            "answer": "B Leo",
            "explanation": "Leo states he will run the projector test.",
        },
    ],
}

_TEST_3 = {
    "test_number": 3,
    "id": "matching-test-3",
    "title": "Section Three: Group presentation",
    "audio": "matching_test3.mp3",
    "instructions": "Who will be responsible for each task? Choose A, B or C.",
    "lines": [
        ("NARRATOR", "Section Three. You will hear two students organizing tasks for a group presentation."),
        ("W", "I can open the talk, unless you prefer to do the introduction."),
        ("M", "No, you are clearer at the start, so keep that."),
        ("W", "Fine. Could you collect the survey statistics from the database?"),
        ("M", "Yes, I will handle the data and turn it into charts."),
        ("W", "Who writes the conclusion slide?"),
        ("M", "Let's write that together so the ending sounds balanced."),
        ("W", "Okay. I will print handouts tonight."),
        ("M", "Great, and I will book the seminar room equipment."),
    ],
    "questions": [
        {
            "id": "q1",
            "render": "select",
            "text": "Giving the introduction",
            "options": ["A Rina", "B Yusuf", "C both of them"],
            "answer": "A Rina",
            "explanation": "Yusuf confirms that Rina should keep the introduction.",
        },
        {
            "id": "q2",
            "render": "select",
            "text": "Collecting survey statistics",
            "options": ["A Rina", "B Yusuf", "C both of them"],
            "answer": "B Yusuf",
            "explanation": "Yusuf agrees to collect data and prepare charts.",
        },
        {
            "id": "q3",
            "render": "select",
            "text": "Writing the conclusion slide",
            "options": ["A Rina", "B Yusuf", "C both of them"],
            "answer": "C both of them",
            "explanation": "They choose to write the conclusion together.",
        },
        {
            "id": "q4",
            "render": "select",
            "text": "Printing handouts",
            "options": ["A Rina", "B Yusuf", "C both of them"],
            "answer": "A Rina",
            "explanation": "Rina explicitly says she will print handouts.",
        },
        {
            "id": "q5",
            "render": "select",
            "text": "Booking presentation equipment",
            "options": ["A Rina", "B Yusuf", "C both of them"],
            "answer": "B Yusuf",
            "explanation": "Yusuf takes responsibility for booking equipment.",
        },
    ],
}

_TEST_4 = {
    "test_number": 4,
    "id": "matching-test-4",
    "title": "Section Three: Wedding preparation",
    "audio": "matching_test4.mp3",
    "instructions": "Who will be responsible for each task? Choose A, B or C.",
    "lines": [
        ("NARRATOR", "Section Three. You will hear a couple assigning tasks for their wedding."),
        ("W", "I thought you might choose the florist, but maybe I should do that."),
        ("M", "Yes, flowers should be your task. I am terrible with colours."),
        ("W", "Then can you call the photographer and confirm the schedule?"),
        ("M", "No problem, I will handle the photographer."),
        ("W", "What about planning the seating chart?"),
        ("M", "That has to be both of us, otherwise relatives complain."),
        ("W", "True. I will also organise the cake tasting."),
        ("M", "Great, and I will arrange transport for elderly guests."),
    ],
    "questions": [
        {
            "id": "q1",
            "render": "select",
            "text": "Choosing the florist",
            "options": ["A Layla", "B Omar", "C both of them"],
            "answer": "A Layla",
            "explanation": "After considering options, they assign flowers to Layla.",
        },
        {
            "id": "q2",
            "render": "select",
            "text": "Contacting the photographer",
            "options": ["A Layla", "B Omar", "C both of them"],
            "answer": "B Omar",
            "explanation": "Omar agrees to confirm the photographer schedule.",
        },
        {
            "id": "q3",
            "render": "select",
            "text": "Planning the seating chart",
            "options": ["A Layla", "B Omar", "C both of them"],
            "answer": "C both of them",
            "explanation": "They say seating must be done jointly.",
        },
        {
            "id": "q4",
            "render": "select",
            "text": "Organising cake tasting",
            "options": ["A Layla", "B Omar", "C both of them"],
            "answer": "A Layla",
            "explanation": "Layla volunteers for cake tasting.",
        },
        {
            "id": "q5",
            "render": "select",
            "text": "Arranging guest transport",
            "options": ["A Layla", "B Omar", "C both of them"],
            "answer": "B Omar",
            "explanation": "Omar states he will handle transport for guests.",
        },
    ],
}

_TEST_5 = {
    "test_number": 5,
    "id": "matching-test-5",
    "title": "Section Three: Office relocation",
    "audio": "matching_test5.mp3",
    "instructions": "Who will be responsible for each task? Choose A, B or C.",
    "lines": [
        ("NARRATOR", "Section Three. You will hear two colleagues planning an office relocation."),
        ("W", "I can email clients about the new address, unless you prefer to do it."),
        ("M", "Please do that. I need to focus on internet installation timing."),
        ("W", "All right. I started the packing checklist too."),
        ("M", "Let's complete packing together this week, room by room."),
        ("W", "Fine. Who will meet the furniture delivery team on move day?"),
        ("M", "I can do that while you supervise the staff briefing."),
        ("W", "Actually I must lead the briefing and also book temporary parking."),
        ("M", "Then I will manage delivery, and parking will be your job."),
    ],
    "questions": [
        {
            "id": "q1",
            "render": "select",
            "text": "Sending clients the new address",
            "options": ["A Sara", "B Bilal", "C both of them"],
            "answer": "A Sara",
            "explanation": "Sara offers and Bilal confirms she should send client emails.",
        },
        {
            "id": "q2",
            "render": "select",
            "text": "Scheduling internet installation",
            "options": ["A Sara", "B Bilal", "C both of them"],
            "answer": "B Bilal",
            "explanation": "Bilal says he must focus on installation timing.",
        },
        {
            "id": "q3",
            "render": "select",
            "text": "Completing the packing process",
            "options": ["A Sara", "B Bilal", "C both of them"],
            "answer": "C both of them",
            "explanation": "They explicitly agree to finish packing together.",
        },
        {
            "id": "q4",
            "render": "select",
            "text": "Managing furniture delivery",
            "options": ["A Sara", "B Bilal", "C both of them"],
            "answer": "B Bilal",
            "explanation": "Bilal takes delivery once Sara confirms her other tasks.",
        },
        {
            "id": "q5",
            "render": "select",
            "text": "Booking temporary parking",
            "options": ["A Sara", "B Bilal", "C both of them"],
            "answer": "A Sara",
            "explanation": "Sara says parking will be her responsibility.",
        },
    ],
}

TESTS = [_TEST_1, _TEST_2, _TEST_3, _TEST_4, _TEST_5]
