"""IELTS-style multiple choice listening tests (Band 6-7+)."""

_TEST_1 = {
    "test_number": 1,
    "id": "mc-test-1",
    "title": "Careers fair briefing",
    "audio": "mc_test1.mp3",
    "instructions": "Questions 1-5. Choose the correct answer, A, B or C.",
    "lines": [
        ("NARRATOR", "Section Two. You will hear a university careers adviser giving a briefing before a careers fair."),
        ("W2", "Morning everyone. This briefing is not to tell you every employer on the list, and it is not a motivational speech. It is to help you use the fair strategically."),
        ("W2", "Some of you think Thursday is mostly about summer placements. There are a few internships, yes, but most stands are recruiting final-year students for graduate jobs starting in autumn."),
        ("W2", "Please arrive at ten when doors open. Last year people who came around noon spent most of their time in queues, and some had to skip their first-choice firms."),
        ("W2", "Bring printed CVs, but do not hand out the same version to everyone. A tailored CV and two focused questions create a much better first impression."),
        ("W2", "About salary: ask eventually, but not in your opening minute. Recruiters told us candidates sounded transactional when pay came before role fit."),
        ("W2", "For clothes, full business suits are optional. Smart casual is fine. However, very casual outfits can make you look unprepared."),
        ("W2", "After each conversation, step aside and write brief notes. By evening, details blur and you may confuse one company with another."),
    ],
    "questions": [
        {
            "id": "q1",
            "render": "radio",
            "text": "What is the main purpose of the briefing?",
            "options": [
                "A  to provide a full list of employers",
                "B  to show students how to approach the event effectively",
                "C  to persuade students to apply for internships",
            ],
            "answer": "B  to show students how to approach the event effectively",
            "explanation": "She says it is not a list of employers or a motivational talk; the focus is practical strategy for using the fair well.",
        },
        {
            "id": "q2",
            "render": "radio",
            "text": "Most organisations at the fair are offering",
            "options": [
                "A  temporary summer work",
                "B  voluntary campus roles",
                "C  permanent graduate positions",
            ],
            "answer": "C  permanent graduate positions",
            "explanation": "Internships are mentioned as limited, while the majority are seeking graduates for roles beginning after graduation.",
        },
        {
            "id": "q3",
            "render": "radio",
            "text": "Why does the adviser recommend arriving early?",
            "options": [
                "A  to avoid long waits for popular recruiters",
                "B  to attend a compulsory opening ceremony",
                "C  to collect printed maps before they run out",
            ],
            "answer": "A  to avoid long waits for popular recruiters",
            "explanation": "She warns that late arrivals spent most of their time queueing and missed preferred companies.",
        },
        {
            "id": "q4",
            "render": "radio",
            "text": "What attitude does the adviser express about discussing salary?",
            "options": [
                "A  It should be avoided completely.",
                "B  It can be raised, but only after discussing suitability.",
                "C  It should be the first topic to save time.",
            ],
            "answer": "B  It can be raised, but only after discussing suitability.",
            "explanation": "She does not ban salary talk; she says timing matters and early focus on pay sounds negative.",
        },
        {
            "id": "q5",
            "render": "radio",
            "text": "What is implied about writing notes after each conversation?",
            "options": [
                "A  it helps students compare employers accurately later",
                "B  it is required by the careers office",
                "C  it impresses recruiters watching nearby",
            ],
            "answer": "A  it helps students compare employers accurately later",
            "explanation": "She says details blur by evening, so note-taking prevents confusion between organisations.",
        },
    ],
}

_TEST_2 = {
    "test_number": 2,
    "id": "mc-test-2",
    "title": "Council recycling information talk",
    "audio": "mc_test2.mp3",
    "instructions": "Questions 1-5. Choose the correct answer, A, B or C.",
    "lines": [
        ("NARRATOR", "Section Two. You will hear a council officer giving a public talk about recycling changes in the district."),
        ("M2", "Thanks for coming. From next month, we are not moving to one mixed recycling container. Households will still separate materials across three bins."),
        ("M2", "The main timetable change is for green bins, which move from Tuesday to Wednesday. Brown food-waste caddies stay on Friday."),
        ("M2", "A common mistake concerns glass. It does not go in the blue paper bin, and it does not go in with plastics. Please use the bottle banks at supermarket car parks."),
        ("M2", "We nearly dropped the food-waste trial last year because contamination was so high. What turned it around was clearer labels on lids and short demonstration videos."),
        ("M2", "About garden waste, we discussed increasing the annual fee from forty pounds to fifty. We decided against that and will keep it at forty this year."),
        ("M2", "If you are unsure about an item, use the council app first. The helpline is still available, but waiting times are long, and the app gives immediate answers."),
        ("M2", "Our aim is not to fine people. We want to cut rejection loads at the sorting plant by making the instructions simpler."),
    ],
    "questions": [
        {
            "id": "q1",
            "render": "radio",
            "text": "Under the updated system, residents will",
            "options": [
                "A  combine all recyclables in one container",
                "B  continue sorting materials into separate bins",
                "C  deliver household recycling to a depot themselves",
            ],
            "answer": "B  continue sorting materials into separate bins",
            "explanation": "He rejects the mixed-bin idea and confirms that three-bin separation remains.",
        },
        {
            "id": "q2",
            "render": "radio",
            "text": "What change is made to collection days?",
            "options": [
                "A  food caddies move to Wednesday",
                "B  green bins move to Wednesday",
                "C  all bins move to Friday",
            ],
            "answer": "B  green bins move to Wednesday",
            "explanation": "Tuesday changes to Wednesday only for green bins, while food-waste caddies remain on Friday.",
        },
        {
            "id": "q3",
            "render": "radio",
            "text": "How should residents dispose of glass bottles?",
            "options": [
                "A  place them with paper and card",
                "B  include them with plastic packaging",
                "C  take them to dedicated collection banks",
            ],
            "answer": "C  take them to dedicated collection banks",
            "explanation": "Both blue-bin and plastic-bin options are explicitly rejected; bottle banks are the approved route.",
        },
        {
            "id": "q4",
            "render": "radio",
            "text": "Why did the food-waste scheme improve?",
            "options": [
                "A  residents were threatened with penalties",
                "B  guidance became easier to understand",
                "C  collections became less frequent",
            ],
            "answer": "B  guidance became easier to understand",
            "explanation": "He says clearer labels and videos reduced contamination, indicating communication quality was the key factor.",
        },
        {
            "id": "q5",
            "render": "radio",
            "text": "What does the officer imply about the council's priority?",
            "options": [
                "A  increasing revenue from charges",
                "B  punishing residents for mistakes",
                "C  reducing rejected recycling through clearer support",
            ],
            "answer": "C  reducing rejected recycling through clearer support",
            "explanation": "He says the goal is not fines but fewer rejected loads, and he emphasizes simple guidance via the app.",
        },
    ],
}

_TEST_3 = {
    "test_number": 3,
    "id": "mc-test-3",
    "title": "Student and tutor research meeting",
    "audio": "mc_test3.mp3",
    "instructions": "Questions 1-5. Choose the correct answer, A, B or C.",
    "lines": [
        ("NARRATOR", "Section Three. You will hear a discussion between a student and his tutor about a research project."),
        ("W2", "Leo, where are you with your project proposal?"),
        ("M", "Behind schedule, honestly. I spent too long reading laboratory studies before accepting my topic has to be fieldwork in the reserve."),
        ("W2", "That is common. Are you still comparing birds and small mammals?"),
        ("M", "No, I dropped mammals. I am examining nesting birds only, because if I keep both groups the project becomes descriptive rather than analytical."),
        ("W2", "Good decision. And your method?"),
        ("M", "I first considered online questionnaires and brief interviews with walkers, but those would give opinions. I need monthly habitat observations and nest counts."),
        ("W2", "Exactly. About timing, your draft is due on 5 April. The 15 April date applies only to students who requested an extension in January."),
        ("M", "Understood. I also found a 2019 survey. Should I use it as evidence?"),
        ("W2", "Use it cautiously for background trends. The sampling method changed, so it cannot carry your main argument."),
    ],
    "questions": [
        {
            "id": "q1",
            "render": "radio",
            "text": "Why did Leo lose time at the start?",
            "options": [
                "A  He focused on the wrong research context.",
                "B  He changed supervisor halfway through.",
                "C  He waited for equipment to be delivered.",
            ],
            "answer": "A  He focused on the wrong research context.",
            "explanation": "He says he concentrated on lab-based reading before realizing his project required fieldwork.",
        },
        {
            "id": "q2",
            "render": "radio",
            "text": "Why did Leo narrow his topic to birds only?",
            "options": [
                "A  Mammal data were unavailable.",
                "B  He wanted to produce deeper analysis.",
                "C  The tutor banned him from studying mammals.",
            ],
            "answer": "B  He wanted to produce deeper analysis.",
            "explanation": "He says keeping both groups would make the study descriptive, so narrowing improves analytical depth.",
        },
        {
            "id": "q3",
            "render": "radio",
            "text": "What method will Leo use for primary data?",
            "options": [
                "A  online public surveys",
                "B  short interviews with visitors",
                "C  scheduled on-site monitoring",
            ],
            "answer": "C  scheduled on-site monitoring",
            "explanation": "Questionnaires and interviews are mentioned then rejected; he chooses monthly observation and nest-count work.",
        },
        {
            "id": "q4",
            "render": "radio",
            "text": "What is Leo's actual deadline for the draft?",
            "options": [
                "A  5 April",
                "B  15 April",
                "C  15 January",
            ],
            "answer": "A  5 April",
            "explanation": "The later date is conditional on an earlier extension request, which Leo did not make.",
        },
        {
            "id": "q5",
            "render": "radio",
            "text": "What is the tutor's view of the 2019 survey?",
            "options": [
                "A  It should be omitted entirely.",
                "B  It can support context but not core claims.",
                "C  It is the most reliable dataset available.",
            ],
            "answer": "B  It can support context but not core claims.",
            "explanation": "She advises limited use because the sampling approach changed, reducing its strength as main evidence.",
        },
    ],
}

_TEST_4 = {
    "test_number": 4,
    "id": "mc-test-4",
    "title": "Museum staff planning meeting",
    "audio": "mc_test4.mp3",
    "instructions": "Questions 1-5. Choose the correct answer, A, B or C.",
    "lines": [
        ("NARRATOR", "Section Three. You will hear a discussion between two museum staff members planning an exhibition."),
        ("W", "Mark, feedback on our coin display was clear: visitors liked the objects, but many left without understanding the historical story."),
        ("M", "I thought about adding longer wall text. But in the textile wing we tried that, and people mostly walked past it."),
        ("W", "So I prefer short audio stations near each case. They cost more than panels, and we considered touchscreens, but the pilot showed audio kept attention longer."),
        ("M", "Now timing. Marketing wants Easter opening, yet conservation says humidity controls will not be stable before 22 March."),
        ("W", "Then we should launch in April. We could push for late March, but that risks damage to borrowed artefacts."),
        ("M", "For schools, should we reuse the lecture theatre?"),
        ("W", "No, the acoustics there were poor. We will use the new ground-floor activity room. Capacity drops from forty to twenty-five, but teachers can actually hear."),
        ("M", "Finance proposed free admission to increase numbers."),
        ("W", "I would keep the six-pound adult ticket and offer free entry only on the first Sunday monthly. That keeps value without excluding people."),
    ],
    "questions": [
        {
            "id": "q1",
            "render": "radio",
            "text": "What solution does Elena support for improving interpretation?",
            "options": [
                "A  longer written labels",
                "B  brief recorded explanations",
                "C  touchscreen quizzes",
            ],
            "answer": "B  brief recorded explanations",
            "explanation": "She rejects long text and notes touchscreens were only considered, while audio was most effective in trials.",
        },
        {
            "id": "q2",
            "render": "radio",
            "text": "Why do they avoid a late-March opening?",
            "options": [
                "A  school bookings are not confirmed",
                "B  advertising material is unfinished",
                "C  environmental conditions may endanger loans",
            ],
            "answer": "C  environmental conditions may endanger loans",
            "explanation": "The humidity system is not ready, and Elena says rushing could harm borrowed objects.",
        },
        {
            "id": "q3",
            "render": "radio",
            "text": "Why do they choose the new activity room for school sessions?",
            "options": [
                "A  It allows much larger groups.",
                "B  It provides clearer sound for teaching.",
                "C  It is closer to the textile gallery.",
            ],
            "answer": "B  It provides clearer sound for teaching.",
            "explanation": "The lecture theatre's poor acoustics are the problem; the new room solves audibility despite smaller capacity.",
        },
        {
            "id": "q4",
            "render": "radio",
            "text": "What is Elena's attitude to ticket pricing?",
            "options": [
                "A  She favors fully free entry every day.",
                "B  She supports a small charge with targeted free access.",
                "C  She wants to raise the standard adult price.",
            ],
            "answer": "B  She supports a small charge with targeted free access.",
            "explanation": "She keeps the six-pound ticket but includes a regular free day, balancing access and perceived value.",
        },
        {
            "id": "q5",
            "render": "radio",
            "text": "What is implied about the meeting decision-making process?",
            "options": [
                "A  They prioritize evidence from previous trials.",
                "B  They follow finance recommendations automatically.",
                "C  They avoid any options that increase costs.",
            ],
            "answer": "A  They prioritize evidence from previous trials.",
            "explanation": "Both the interpretation format and pricing choices are justified using outcomes from earlier museum pilots and data.",
        },
    ],
}

_TEST_5 = {
    "test_number": 5,
    "id": "mc-test-5",
    "title": "Podcast on a coastal reserve",
    "audio": "mc_test5.mp3",
    "instructions": "Questions 1-5. Choose the correct answer, A, B or C.",
    "lines": [
        ("NARRATOR", "Section Two. You will hear part of a podcast about management at a coastal nature reserve."),
        ("M2", "Today I am with reserve warden Sarah Lim at North Haven Coast."),
        ("W2", "Fifteen years ago our biggest fear was oil pollution from tankers. That risk has dropped, but disturbance from leisure use, especially drones near nesting cliffs, is now the critical issue."),
        ("M2", "Some listeners might expect you to close the reserve completely in spring."),
        ("W2", "We considered that, but a full ban would reduce public support. Instead we direct people onto boardwalks and close only the most sensitive breeding zones."),
        ("M2", "The dog rules have changed too, right?"),
        ("W2", "Yes. Dogs used to be allowed on all beaches all year. Now from April to September they must stay near the car park; from October to March they can use marked beach areas."),
        ("M2", "I also heard the visitor centre would move to the harbour."),
        ("W2", "That relocation plan was cancelled when funding failed. We are refurbishing the current centre and expect reopening in September, not August."),
        ("M2", "Finally, what support matters most: donations, social media promotion, or volunteering?"),
        ("W2", "All help is welcome, but our biggest gap is volunteers for dawn bird counts. Those counts guide every management decision we make."),
    ],
    "questions": [
        {
            "id": "q1",
            "render": "radio",
            "text": "According to Sarah, what is currently the main pressure on seabirds?",
            "options": [
                "A  shipping-related pollution",
                "B  disturbance from visitor behavior",
                "C  lack of nesting materials",
            ],
            "answer": "B  disturbance from visitor behavior",
            "explanation": "Oil pollution is presented as a past concern, while current pressure comes from recreation activities such as drone use.",
        },
        {
            "id": "q2",
            "render": "radio",
            "text": "How does the reserve manage public access in breeding season?",
            "options": [
                "A  by banning all visitors temporarily",
                "B  by allowing unrestricted movement",
                "C  by directing routes and restricting key areas",
            ],
            "answer": "C  by directing routes and restricting key areas",
            "explanation": "She rejects a full closure and explains that boardwalk routing plus selective closures is the chosen approach.",
        },
        {
            "id": "q3",
            "render": "radio",
            "text": "What is true about dogs between April and September?",
            "options": [
                "A  they may use beaches if kept on leads",
                "B  they are limited to the parking-zone area",
                "C  they are prohibited from entering the reserve at all",
            ],
            "answer": "B  they are limited to the parking-zone area",
            "explanation": "Summer access is restricted to the car park vicinity; beach access applies in the October-March period.",
        },
        {
            "id": "q4",
            "render": "radio",
            "text": "What happened to the visitor-centre relocation plan?",
            "options": [
                "A  It was postponed until next summer.",
                "B  It was replaced by upgrading the existing site.",
                "C  It was approved but delayed by weather.",
            ],
            "answer": "B  It was replaced by upgrading the existing site.",
            "explanation": "She says funding failed, so the harbour move was cancelled and refurbishment of the current centre is proceeding.",
        },
        {
            "id": "q5",
            "render": "radio",
            "text": "What does Sarah imply is most valuable for reserve management?",
            "options": [
                "A  volunteers collecting field data",
                "B  one-off fundraising drives",
                "C  promotional posts online",
            ],
            "answer": "A  volunteers collecting field data",
            "explanation": "Donations and promotion are acknowledged, but she says dawn counting volunteers fill the key operational gap.",
        },
    ],
}

TESTS = [_TEST_1, _TEST_2, _TEST_3, _TEST_4, _TEST_5]
