"""Short-answer listening practice sets - IELTS Listening Section 1 style."""

_TEST_1 = {
    "test_number": 1,
    "id": "short-test-1",
    "title": "Theatre membership enquiry",
    "audio": "short_test1.mp3",
    "instructions": "Questions 1-5. Write NO MORE THAN TWO WORDS AND/OR A NUMBER for each answer.",
    "lines": [
        ("NARRATOR", "Section One. You will hear a phone conversation about theatre membership. Answer questions 1 to 5."),
        ("W", "Grand City Theatre membership office, how can I help?"),
        ("M", "Hi, I am thinking of joining and wanted to check the benefits."),
        ("W", "Members can book tickets 48 hours before public sales open."),
        ("M", "I thought it was only 24 hours."),
        ("W", "It used to be, but it is 48 now."),
        ("M", "How many seats can one member reserve per show?"),
        ("W", "Up to 6 tickets. Four was the old limit."),
        ("M", "And the annual membership fee?"),
        ("W", "It is 65 pounds now, not 60."),
        ("M", "Are any performances excluded from membership booking?"),
        ("W", "Only the New Year gala is excluded."),
        ("M", "Where do members collect their tickets on performance nights?"),
        ("W", "At the side entrance desk, not the main box office."),
    ],
    "questions": [
        {"id": "q1", "render": "text", "text": "How far in advance can members reserve seats?", "answer": ["48 hours", "48"], "explanation": "The adviser confirms the current early-booking window is 48 hours."},
        {"id": "q2", "render": "text", "text": "Maximum tickets allowed per production:", "answer": ["6"], "explanation": "Four is old information; the current maximum is six."},
        {"id": "q3", "render": "text", "text": "Current yearly membership cost:", "answer": ["65", "65 pounds"], "explanation": "The final confirmed fee is 65 pounds."},
        {"id": "q4", "render": "text", "text": "Which event is not covered by membership booking?", "answer": ["new year gala", "gala"], "explanation": "The New Year gala is the only excluded event."},
        {"id": "q5", "render": "text", "text": "Where should members collect tickets?", "answer": ["side entrance", "entrance desk"], "explanation": "Collection is at the side entrance desk, not the main box office."},
    ],
}

_TEST_2 = {
    "test_number": 2,
    "id": "short-test-2",
    "title": "Swimming pool information call",
    "audio": "short_test2.mp3",
    "instructions": "Questions 1-5. Write NO MORE THAN TWO WORDS AND/OR A NUMBER for each answer.",
    "lines": [
        ("NARRATOR", "Section One. You will hear a phone call about swimming pool rules. Answer questions 1 to 5."),
        ("W", "Hello, I am bringing my daughter tomorrow and need to check your rules."),
        ("M", "Sure, what do you need to know?"),
        ("W", "At what age can children swim without an adult? Is it 9?"),
        ("M", "No, they must be at least 10."),
        ("W", "Are swim caps compulsory in family sessions?"),
        ("M", "Compulsory in lane sessions, but only recommended for family sessions."),
        ("W", "Family swim starts at 3:15, right?"),
        ("M", "It now starts at 3:30 and ends at 5."),
        ("W", "Can children use large inflatables?"),
        ("M", "Small armbands are fine, but large inflatables are not allowed in the main pool."),
        ("W", "What coin is needed for lockers? I have a 1 pound coin."),
        ("M", "You need a 2 pound coin now."),
        ("W", "Thanks, that is very helpful."),
    ],
    "questions": [
        {"id": "q1", "render": "text", "text": "Minimum unaccompanied swimming age:", "answer": ["10"], "explanation": "The staff member corrects 9 and confirms 10."},
        {"id": "q2", "render": "text", "text": "For family sessions, swim caps are:", "answer": ["recommended"], "explanation": "They are recommended, not compulsory."},
        {"id": "q3", "render": "text", "text": "Family swim start time:", "answer": ["3:30"], "explanation": "3:15 is incorrect; 3:30 is the current start time."},
        {"id": "q4", "render": "text", "text": "Large inflatables are banned in which area?", "answer": ["main pool"], "explanation": "The restriction applies to the main pool."},
        {"id": "q5", "render": "text", "text": "Locker coin value required:", "answer": ["2", "2 pounds"], "explanation": "The locker system now requires a 2 pound coin."},
    ],
}

_TEST_3 = {
    "test_number": 3,
    "id": "short-test-3",
    "title": "Job interview scheduling call",
    "audio": "short_test3.mp3",
    "instructions": "Questions 1-5. Write NO MORE THAN TWO WORDS AND/OR A NUMBER for each answer.",
    "lines": [
        ("NARRATOR", "Section One. You will hear a recruiter arranging a job interview by phone. Answer questions 1 to 5."),
        ("M", "Hello, may I speak to Leila Hassan?"),
        ("W", "Speaking."),
        ("M", "I am calling from Easton Media to arrange your interview."),
        ("W", "Great. Is there a slot on Wednesday?"),
        ("M", "Wednesday is full. We can do Thursday at 2:40 p.m."),
        ("W", "Fine. Is it at your city office?"),
        ("M", "No, interviews are at the Riverside branch this week."),
        ("W", "Should I bring references and certificates?"),
        ("M", "Please bring photo ID and your portfolio. References can be emailed later."),
        ("W", "How long should I allow?"),
        ("M", "Around 45 minutes, including a short task."),
        ("W", "Thanks, I will be there."),
        ("M", "Great, see you Thursday."),
    ],
    "questions": [
        {"id": "q1", "render": "text", "text": "Candidate surname:", "answer": ["hassan"], "explanation": "The caller asks for Leila Hassan."},
        {"id": "q2", "render": "text", "text": "Interview day confirmed:", "answer": ["thursday"], "explanation": "Wednesday is unavailable; Thursday is confirmed."},
        {"id": "q3", "render": "text", "text": "Interview start time:", "answer": ["2:40"], "explanation": "The recruiter gives 2:40 p.m. as the appointment time."},
        {"id": "q4", "render": "text", "text": "Interview location branch:", "answer": ["riverside"], "explanation": "The candidate is told to attend the Riverside branch."},
        {"id": "q5", "render": "text", "text": "Expected interview duration:", "answer": ["45 minutes", "45"], "explanation": "Total time is around 45 minutes."},
    ],
}

_TEST_4 = {
    "test_number": 4,
    "id": "short-test-4",
    "title": "Library loan enquiry",
    "audio": "short_test4.mp3",
    "instructions": "Questions 1-5. Write NO MORE THAN TWO WORDS AND/OR A NUMBER for each answer.",
    "lines": [
        ("NARRATOR", "Section One. You will hear a student calling the library about borrowing a book. Answer questions 1 to 5."),
        ("W", "Hi, I need a book from another campus library."),
        ("M", "You can request that through our inter-library service."),
        ("W", "Do I need staff approval first?"),
        ("M", "No, just submit the request online."),
        ("W", "Is the charge still 5 pounds?"),
        ("M", "No, standard requests are 4 pounds."),
        ("W", "How soon does it usually arrive?"),
        ("M", "Not in two days - usually about 6 working days."),
        ("W", "And how long can I keep it?"),
        ("M", "The loan period is 21 days."),
        ("W", "Where do I pick it up when it arrives?"),
        ("M", "From the reservations shelf near the entrance."),
        ("W", "Perfect, thank you."),
    ],
    "questions": [
        {"id": "q1", "render": "text", "text": "How should students submit the request?", "answer": ["online"], "explanation": "The library officer says requests must be submitted online."},
        {"id": "q2", "render": "text", "text": "Standard inter-library fee per item:", "answer": ["4", "4 pounds"], "explanation": "5 pounds is outdated; the current charge is 4 pounds."},
        {"id": "q3", "render": "text", "text": "Typical delivery period:", "answer": ["6 days", "6"], "explanation": "The speaker corrects the fast estimate to about 6 working days."},
        {"id": "q4", "render": "text", "text": "Loan length:", "answer": ["21 days", "21"], "explanation": "The item can be kept for 21 days."},
        {"id": "q5", "render": "text", "text": "Collection point for requested books:", "answer": ["reservations shelf", "shelf"], "explanation": "Pick-up is from the reservations shelf by the entrance."},
    ],
}

_TEST_5 = {
    "test_number": 5,
    "id": "short-test-5",
    "title": "Dental appointment booking",
    "audio": "short_test5.mp3",
    "instructions": "Questions 1-5. Write NO MORE THAN TWO WORDS AND/OR A NUMBER for each answer.",
    "lines": [
        ("NARRATOR", "Section One. You will hear a patient booking a dental appointment by phone. Answer questions 1 to 5."),
        ("M", "Good morning, Maple Dental Clinic."),
        ("W", "Hello, this is Sara Malik. I need a check-up appointment."),
        ("M", "Of course. Would Friday suit you?"),
        ("W", "Yes, if possible."),
        ("M", "Friday is full now. Earliest is Monday the 22nd at 10:50."),
        ("W", "Is that with Dr Green?"),
        ("M", "Dr Green is away, so you will see Dr Ahmed."),
        ("W", "Should I arrive at 10:50 exactly?"),
        ("M", "Please come 10 minutes early for your form."),
        ("W", "If I need an X-ray, how much is the extra charge?"),
        ("M", "It is 30 pounds, not 25."),
        ("W", "Okay, please book that slot."),
        ("M", "Done. We will text you a reminder."),
    ],
    "questions": [
        {"id": "q1", "render": "text", "text": "Patient surname:", "answer": ["malik"], "explanation": "The caller identifies herself as Sara Malik."},
        {"id": "q2", "render": "text", "text": "Appointment date (day of month):", "answer": ["22", "22nd"], "explanation": "Friday is unavailable; Monday the 22nd is booked."},
        {"id": "q3", "render": "text", "text": "Appointment time:", "answer": ["10:50"], "explanation": "The receptionist confirms 10:50 as the appointment time."},
        {"id": "q4", "render": "text", "text": "Minutes to arrive early:", "answer": ["10"], "explanation": "The patient is asked to arrive 10 minutes early."},
        {"id": "q5", "render": "text", "text": "Extra fee for X-ray:", "answer": ["30", "30 pounds"], "explanation": "25 is rejected; the final X-ray charge is 30 pounds."},
    ],
}

TESTS = [_TEST_1, _TEST_2, _TEST_3, _TEST_4, _TEST_5]
