# Generated by Django 5.2.12 on 2026-04-04 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReadingPassage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('topic', models.CharField(choices=[('environment', 'Environment'), ('health', 'Health'), ('technology', 'Technology'), ('education', 'Education'), ('society', 'Society')], max_length=32)),
                ('level', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3')])),
                ('content', models.TextField(help_text='Full passage text. Use blank lines between paragraphs.')),
            ],
            options={
                'ordering': ['topic', 'level', 'title'],
            },
        ),
    ]
