# Generated by Django 5.2.12 on 2026-04-04 03:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reading', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReadingQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField()),
                ('prompt', models.TextField()),
                ('option_a', models.CharField(max_length=500)),
                ('option_b', models.CharField(max_length=500)),
                ('option_c', models.CharField(max_length=500)),
                ('option_d', models.CharField(max_length=500)),
                ('correct_letter', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=1)),
                ('passage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='reading.readingpassage')),
            ],
            options={
                'ordering': ['passage', 'order'],
                'constraints': [models.UniqueConstraint(fields=('passage', 'order'), name='reading_unique_question_order_per_passage')],
            },
        ),
    ]
