"""Spoken scripts for the Listening audio of Practice Tests 2-5.

SCRIPTS maps (test_number, section_number) -> list of (speaker, text) lines, in
the same ``(speaker, text)`` shape Test 1 uses in ``listening_content.py``.
Speakers map to OpenAI TTS voices via VOICES in listening_content.py:
    NARRATOR, W, W2 (female), M, M2 (male).

Every answer for a section is spoken aloud, in the same order as the questions,
so the recording is genuinely answerable. The per-section MP3 files are produced
by ``manage.py prepare_test_listening_audio`` and saved to
``static/listening_audio/testN_sX.mp3``.
"""

SCRIPTS: dict[tuple[int, int], list[tuple[str, str]]] = {

    # ===================================================================== #
    #  TEST 2
    # ===================================================================== #
    (2, 1): [
        ("NARRATOR", "Section 1. You will hear a telephone conversation between a man enquiring about a holiday cottage and a letting agent. First, you have some time to look at questions 1 to 10."),
        ("W", "Good afternoon, Westcombe Holiday Lettings, Claire speaking. How can I help?"),
        ("M", "Hi there. I'm interested in one of your cottages for a week in the summer. Could you give me a few details?"),
        ("W", "Of course. The one most people ask about is called Rose Cottage."),
        ("M", "Sorry, was that Rose? R-O-S-E?"),
        ("W", "That's right, Rose Cottage. It's in a little village called Ashford — A-S-H-F-O-R-D."),
        ("M", "Lovely. And how many bedrooms does it have?"),
        ("W", "It has three bedrooms, so it sleeps up to six people comfortably."),
        ("M", "Great. Is there anything included, like a pool or anything?"),
        ("W", "There's no swimming pool or sauna, I'm afraid, but the cottage does come with free Wi-Fi throughout."),
        ("M", "Free Wi-Fi, perfect. And what does it cost?"),
        ("W", "In the low season it's four hundred and fifty pounds per week."),
        ("M", "Four hundred and fifty. And when would it be available?"),
        ("W", "It's free from the twelfth of June onwards."),
        ("M", "The twelfth, good. Oh — we have a small dog. Is that a problem?"),
        ("W", "Pets are welcome, but we do ask for a deposit in case of any damage."),
        ("M", "That's fair, a deposit is fine. How would we get there by train?"),
        ("W", "The nearest railway station is Bridgwater — B-R-I-D-G-W-A-T-E-R — about ten minutes away by taxi."),
        ("M", "Bridgwater, got it. And who's the owner?"),
        ("W", "The owner is Mrs Patterson — that's P-A-T-T-E-R-S-O-N. She lives nearby and looks after the keys."),
        ("M", "And how do I confirm the booking?"),
        ("W", "To confirm, you just need to pay a twenty per cent deposit, and the rest is due on arrival."),
        ("M", "A twenty per cent deposit — that's clear. Thank you very much."),
    ],
    (2, 2): [
        ("NARRATOR", "Section 2. You will hear a guide welcoming visitors to a new science discovery centre. First, you have some time to look at questions 11 to 20."),
        ("W2", "Hello everyone, and welcome to the Riverside Science Discovery Centre. Let me point out where everything is on the map in your leaflet before you set off."),
        ("W2", "We're standing here at the entrance, at the bottom of the map. If you walk straight ahead, up the central path, the large hall at the very top is the Space Gallery — that's area B."),
        ("W2", "Over on the left-hand side, the room marked D is our Demonstration Theatre, where the live shows take place."),
        ("W2", "Right in the middle, that round room marked E, is the Experiment Lab — the hands-on area children always love."),
        ("W2", "And finally, on your way out, in the bottom right corner, area F is the Gift Shop."),
        ("W2", "A few practical things. We're open every day except Monday, when the centre is closed for maintenance."),
        ("W2", "The planetarium shows run all day, and the first show starts at half past ten in the morning."),
        ("W2", "Please feel free to take photographs anywhere, but we do ask that you don't bring food into the galleries — there's plenty of room to eat in the cafe instead."),
        ("W2", "If you get separated from your group, just make your way to the information desk near the entrance and we'll help you."),
        ("W2", "We also run a rocket-building workshop. It costs three pounds per child, and it's very popular."),
        ("W2", "Because places fill up fast, I'd strongly recommend booking the workshop at least a week ahead rather than on the day."),
        ("W2", "Right — enjoy your visit, and do ask the staff in red shirts if you need anything."),
    ],
    (2, 3): [
        ("NARRATOR", "Section 3. You will hear two geography students, Maya and Daniel, planning a field trip with their tutor. First, you have some time to look at questions 21 to 30."),
        ("M2", "So, Maya, Daniel — let's sort out who does what for the coastal field trip. There's quite a bit to prepare."),
        ("W", "I'm happy to start. I'll take care of the risk assessment, since I did one last year."),
        ("M2", "Good, Maya on the risk assessment. Daniel?"),
        ("M", "I'll check the tide times so we know when it's safe to be on the beach."),
        ("M2", "Excellent, Daniel on tide times. What about equipment?"),
        ("M", "I can do that too — I'll borrow the GPS units from the department store cupboard."),
        ("M2", "Fine, Daniel on the GPS units as well. And the write-up?"),
        ("W", "We thought we'd write the methods section together, actually — both of us."),
        ("M2", "That works well — the two of you on the methods section. Now, about the site. You suggested Sandy Cove first?"),
        ("M", "We did, but we've changed our minds. The access there is unsafe at high tide, so we'd rather not risk it."),
        ("M2", "Sensible — safety comes first. So where instead?"),
        ("W", "We'll collect our samples along a shoreline transect at the next bay."),
        ("M2", "A shoreline transect, good. And your main measurement?"),
        ("W", "We're focusing on sediment size, comparing the top and bottom of the beach."),
        ("M2", "Sediment size, right. One tip — any photographs you take must include a scale, like a ruler, or they're useless for the report."),
        ("M", "A scale in every photo, noted."),
        ("M2", "When can you get the draft report to me?"),
        ("W", "We'll have the draft ready by Friday."),
        ("M2", "Friday's fine. One last thing — last time, your group needed to improve the statistical analysis. Do build that in this time."),
        ("M", "We will, definitely stronger statistical analysis."),
    ],
    (2, 4): [
        ("NARRATOR", "Section 4. You will hear part of a lecture on storing renewable energy. First, you have some time to look at questions 31 to 40."),
        ("M2", "Good morning. Today we're looking at how we store electricity from renewable sources, and why no single method is enough on its own."),
        ("M2", "Let's start with lithium-ion batteries — the kind in your phone, scaled up. Their great strength is their rapid response: they can deliver power within milliseconds."),
        ("M2", "Their main limitation, though, is cost — they remain expensive for storing very large amounts of energy."),
        ("M2", "Next, pumped hydro, where water is pumped uphill and released to drive turbines. Its big advantage is its large capacity — it can store enormous amounts of energy."),
        ("M2", "The drawback is that it needs suitable geography: you need mountains and reservoirs."),
        ("M2", "Then there's hydrogen, made by splitting water. Its key advantage is seasonal storage — you can keep energy from summer to use in winter."),
        ("M2", "Its weakness, however, is efficiency: a lot of energy is lost in converting electricity to hydrogen and back again."),
        ("M2", "Why does all this matter? Because grid operators must balance supply and demand every single second of the day."),
        ("M2", "And that becomes much harder when electricity comes from variable sources like wind and solar, which don't produce steadily."),
        ("M2", "So where do batteries fit? The evidence is clear: batteries are best for short-term balancing — smoothing out minute-by-minute changes — not for storing power across months."),
        ("M2", "The future, then, will almost certainly rely on a portfolio of technologies working together."),
        ("M2", "My main conclusion is this: good storage policy should focus on matching each technology to the right time scale, rather than betting on one solution."),
    ],

    # ===================================================================== #
    #  TEST 3
    # ===================================================================== #
    (3, 1): [
        ("NARRATOR", "Section 1. You will hear a man joining his local public library, talking to a librarian. First, you have some time to look at questions 1 to 10."),
        ("W", "Hello, welcome to Merton Public Library. Would you like to become a member?"),
        ("M", "Yes please. What do you need from me?"),
        ("W", "Just a few details. Can I take your surname?"),
        ("M", "It's Henderson — H-E-N-D-E-R-S-O-N."),
        ("W", "Thank you, Mr Henderson. And your address?"),
        ("M", "It's forty-eight Merton Road — same name as the library, funnily enough. M-E-R-T-O-N."),
        ("W", "And the postcode?"),
        ("M", "It's B-R-six, seven-P-L. So BR6 7PL."),
        ("W", "Lovely. Now, what kind of membership would you like — adult, student or family?"),
        ("M", "I'm at college, so the student one, please."),
        ("W", "Student membership it is. That has a small fee of twelve pounds a year."),
        ("M", "Twelve pounds, that's fine."),
        ("W", "I'll just need proof of your address — a utility bill is ideal, like gas or electricity."),
        ("M", "I've got a utility bill here. How many things can I borrow at once?"),
        ("W", "As a new member you can borrow six items at a time."),
        ("M", "Six, great. And if I'm late returning them?"),
        ("W", "There's a late charge of twenty pence per day, per item."),
        ("M", "Twenty pence a day, noted. What are your opening hours?"),
        ("W", "We're open late on Thursdays — we don't close until eight o'clock."),
        ("M", "Eight o'clock on Thursdays, good. And the computers?"),
        ("W", "The computer room is free, but you must book it online in advance — you can't just turn up."),
        ("M", "Book online, understood. Thanks very much."),
    ],
    (3, 2): [
        ("NARRATOR", "Section 2. You will hear a radio announcement about a local food festival. First, you have some time to look at questions 11 to 20."),
        ("M2", "And now for what's on this weekend — the Riverside Food Festival is back, and here's your guide to the site. Picture the map in this week's local paper."),
        ("M2", "As you come through the main gate at the bottom left, head up the path. The first big tent you'll see, marked B, is the Chef Demonstration Stage, where top cooks show their skills."),
        ("M2", "Over to the left, the area marked D is the Children's Cooking Tent, with activities all day."),
        ("M2", "In the centre, the stand marked E is the Information Desk — go there with any questions."),
        ("M2", "And up in the top right, area C, is the Picnic Area, where you can sit and enjoy what you've bought."),
        ("M2", "Now, the timing. The festival begins on Friday evening with an opening ceremony."),
        ("M2", "Advance tickets cost just eight pounds if you book online before Friday."),
        ("M2", "If you're driving, please don't use the station car park — instead, park on the school field, which is free for festival visitors."),
        ("M2", "To cut down on waste, drinks come in reusable cups, with a two-pound deposit you get back when you return the cup."),
        ("M2", "And don't miss Sunday's finale — a baking competition open to anyone, with prizes for the best cakes."),
        ("M2", "One more thing for dog owners: dogs are very welcome, but they must be kept on leads at all times."),
        ("M2", "So come along, bring your appetite, and we'll see you by the river."),
    ],
    (3, 3): [
        ("NARRATOR", "Section 3. You will hear a student discussing her dissertation plan with her tutor. First, you have some time to look at questions 21 to 30."),
        ("M2", "Right, Emma, I've read your dissertation proposal. Let's go through it section by section."),
        ("W", "Thanks. I know it still needs work."),
        ("M2", "Let's start with your research question. Honestly, it's too broad at the moment — you need to narrow the focus considerably."),
        ("W", "Okay, narrow the research question. What about my literature review?"),
        ("M2", "The review is solid, but it relies on older studies. You should add some more recent sources from the last five years."),
        ("W", "More recent sources, got it. And the questionnaire?"),
        ("M2", "Before you send it out widely, I'd collect some pilot data first — test it on a few people to spot any problems."),
        ("W", "So pilot the questionnaire. And you mentioned my final talk?"),
        ("M2", "Yes — for the final presentation, I think you should change the presentation style; it's a bit text-heavy."),
        ("W", "Change the presentation, noted."),
        ("M2", "Now remind me of your actual topic?"),
        ("W", "It's about library use among first-year students — how often they actually use it."),
        ("M2", "Library use among first-years, good. How big a sample are you aiming for?"),
        ("W", "I want students from three different faculties, to get a range."),
        ("M2", "Three faculties is sensible. And the interviews?"),
        ("W", "Each interview should last about twenty minutes, I think."),
        ("M2", "Twenty minutes is about right. One warning though — be careful with email responses; they can be biased, because only keen students reply."),
        ("W", "True, email replies could be biased. When should I get my revised plan to you?"),
        ("M2", "Let's say by Wednesday next week."),
        ("W", "Wednesday, fine. Where should I put the timetable?"),
        ("M2", "Just put the timetable in an appendix at the back, not in the main text."),
        ("W", "In an appendix — perfect, thank you."),
    ],
    (3, 4): [
        ("NARRATOR", "Section 4. You will hear part of a lecture about life in the deep sea. First, you have some time to look at questions 31 to 40."),
        ("W2", "Today we explore one of the least-known environments on Earth: the deep sea, and the remarkable ways its creatures survive."),
        ("W2", "Let's begin with bioluminescence — the ability to produce light. Its main purpose is communication: animals use flashes to find mates or warn off rivals."),
        ("W2", "A classic example is the anglerfish, which dangles a glowing lure to attract its prey."),
        ("W2", "A second adaptation is a slow metabolism. Its purpose is to conserve energy, because food is extremely scarce down there."),
        ("W2", "Third, many deep-sea organisms have pressure-resistant enzymes. Their purpose is to maintain function — to keep the body's chemistry working under crushing pressure."),
        ("W2", "We see this especially in deep-sea microbes, which thrive where almost nothing else can."),
        ("W2", "Now, conditions. Below about a thousand metres, sunlight is virtually absent — it's permanent darkness."),
        ("W2", "Food mostly drifts down from above as tiny particles, which scientists vividly call marine snow."),
        ("W2", "How do we study all this? Remotely operated vehicles are invaluable, mainly because they can stay underwater far longer than human divers ever could."),
        ("W2", "But there's growing concern. Deep-sea mining could disturb fragile habitats that may take centuries to recover."),
        ("W2", "So the message of today's lecture is that the deep sea is biologically rich but extremely vulnerable, and we must explore it with great care."),
    ],

    # ===================================================================== #
    #  TEST 4
    # ===================================================================== #
    (4, 1): [
        ("NARRATOR", "Section 1. You will hear a woman enrolling in an evening course by telephone. First, you have some time to look at questions 1 to 10."),
        ("W", "Good evening, Community Learning Centre, this is the enrolment line."),
        ("M", "Hi, I'd like to sign up for one of your cookery courses."),
        ("W", "Lovely. Which one were you thinking of?"),
        ("M", "The Italian cooking course, please."),
        ("W", "Italian cooking — a great choice. That class runs on Tuesday evenings."),
        ("M", "Tuesdays, that suits me. How long does the course last?"),
        ("W", "It runs for eight weeks in total."),
        ("M", "Eight weeks, fine. Is it suitable for someone who can barely boil an egg?"),
        ("W", "Absolutely — the main reason people pick it is that it has a beginner group, separate from the more advanced cooks."),
        ("M", "A beginner group — that's exactly what I need. What's the fee?"),
        ("W", "The course fee is ninety-six pounds."),
        ("M", "Ninety-six pounds. Does that include ingredients?"),
        ("W", "It includes a recipe booklet you keep, and the ingredients for each class."),
        ("M", "A recipe booklet, nice. Do I need to bring anything?"),
        ("W", "Just bring an apron — we provide all the knives and pans here."),
        ("M", "An apron, got it. Who's the teacher?"),
        ("W", "Your tutor is Chef Lombardi — that's L-O-M-B-A-R-D-I."),
        ("M", "Lombardi, lovely. How do I pay?"),
        ("W", "You can pay online using the reference COOK four-one-seven. So that's the word COOK, then 417."),
        ("M", "Reference COOK 417, noted. And if I need to cancel?"),
        ("W", "If you cancel, please do it at least forty-eight hours before the first class for a refund."),
        ("M", "Forty-eight hours before — understood. Thank you!"),
    ],
    (4, 2): [
        ("NARRATOR", "Section 2. You will hear a ranger introducing a guided walk at a nature reserve. First, you have some time to look at questions 11 to 20."),
        ("W2", "Morning, everyone, and welcome to Oakmere Nature Reserve. Before we set off, let me show you the route on the map at the start of your leaflet."),
        ("W2", "We begin here at the car park, in the bottom left, which is area A."),
        ("W2", "From there the trail leads up to the large lake in the middle of the map — that's the Lake Viewpoint, marked B, and it's our first stop."),
        ("W2", "Carry on and you'll reach the round patch of trees in the top right, area C, which is the old Oak Wood."),
        ("W2", "Then the path loops down to the building in the bottom right, area E — that's the Bird Hide, where we'll spend a while watching quietly."),
        ("W2", "The full walk lasts about two hours, so pace yourselves."),
        ("W2", "It can get muddy, so I hope you've all got waterproof shoes on."),
        ("W2", "Now, what might we see? At this time of year, the highlight is the migrating geese arriving on the lake in their hundreds."),
        ("W2", "Please enjoy the wild flowers, but don't pick flowers — leave them for others and for the insects."),
        ("W2", "If there's ever an emergency, look for the phone boxes — they're painted bright yellow and easy to spot."),
        ("W2", "And at the end, back near the entrance, you can buy local honey produced right here on the reserve."),
        ("W2", "Right — keep together, and let's begin."),
    ],
    (4, 3): [
        ("NARRATOR", "Section 3. You will hear two students discussing a project on sustainable architecture with their tutor. First, you have some time to look at questions 21 to 30."),
        ("M2", "So, you're comparing three green buildings on campus. Remind me which feature goes with which building."),
        ("W", "Well, the library has the green roof — the one planted with grass and flowers."),
        ("M2", "Right, green roof on the library. And the next feature?"),
        ("M", "The sports centre uses natural ventilation — it cools itself without air conditioning."),
        ("M2", "Natural ventilation at the sports centre, good."),
        ("W", "And the student residence has rainwater recycling, collecting rain for the toilets."),
        ("M2", "Rainwater recycling in the residence. What about solar shading?"),
        ("M", "That's the library again — those angled panels that keep the sun off the windows."),
        ("M2", "So solar shading also at the library. Now, about your first draft — can I be honest?"),
        ("W", "Please do."),
        ("M2", "The main problem is that it's too descriptive. You describe each building but don't analyse the data."),
        ("M", "Fair — too descriptive. How do we fix that?"),
        ("M2", "Compare the predicted energy use with the actual energy use, and discuss the gap."),
        ("W", "Predicted versus actual energy use, got it."),
        ("M2", "I'd also recommend interviewing the building manager — they'll know how it really performs."),
        ("M", "Interview the building manager, good idea. Should we cut anything?"),
        ("M2", "Yes — remove the historical background section. It's interesting but irrelevant."),
        ("W", "We'll cut the historical background. How long should the talk be?"),
        ("M2", "Your presentation should last fifteen minutes, plus questions."),
        ("M", "Fifteen minutes. And the conclusion?"),
        ("M2", "Make sure the conclusion focuses on design principles others could reuse, not just your opinions."),
        ("W", "Focus on design principles — thank you, that's really helpful."),
    ],
    (4, 4): [
        ("NARRATOR", "Section 4. You will hear part of a lecture on the history of timekeeping. First, you have some time to look at questions 31 to 40."),
        ("M2", "Today we trace how humans have measured time, and how each device improved on the last."),
        ("M2", "We begin with sundials. Their great strength was that they were simple — no moving parts, just a shadow on a marked surface."),
        ("M2", "But they had an obvious weakness: in cloudy weather, with no sun, they were useless, and of course they didn't work at night."),
        ("M2", "Then came mechanical clocks. Their key strength was that they were independent — they kept running whatever the weather or time of day."),
        ("M2", "Their weakness, however, was friction: the moving parts wore down and the clocks gradually lost accuracy."),
        ("M2", "Finally, atomic clocks. Their outstanding strength is accuracy — they lose less than a second over millions of years."),
        ("M2", "Of course, they're also complex and expensive, which is the trade-off."),
        ("M2", "Let's think about why timekeeping mattered. Early societies used it to organise farming and religion — when to plant, and when to hold ceremonies."),
        ("M2", "Later, pendulum clocks improved matters by greatly reducing error in everyday timekeeping."),
        ("M2", "A real turning point came with the railways. They created the need for standard time, because timetables crossed many local time zones and caused confusion."),
        ("M2", "And today, our navigation systems depend on extremely precise signals from atomic clocks in satellites."),
        ("M2", "So the lesson is this: accurate timekeeping has become less visible in daily life, yet more essential than ever."),
    ],

    # ===================================================================== #
    #  TEST 5
    # ===================================================================== #
    (5, 1): [
        ("NARRATOR", "Section 1. You will hear a man making a hotel reservation by telephone. First, you have some time to look at questions 1 to 10."),
        ("W", "Good morning, Harbour View Hotel, reservations. How can I help?"),
        ("M", "Hello, I'd like to book a room, please."),
        ("W", "Certainly. Can I take your surname?"),
        ("M", "It's Collins — C-O-L-L-I-N-S."),
        ("W", "Thank you, Mr Collins. When would you like to arrive?"),
        ("M", "We'd arrive on the fourteenth of May."),
        ("W", "The fourteenth of May. And for how many nights?"),
        ("M", "Three nights, please."),
        ("W", "Three nights. What sort of room would you like?"),
        ("M", "Do you have a double with a nice view?"),
        ("W", "We do — I'd suggest the garden-view double, which is lovely and quiet."),
        ("M", "The garden-view double sounds perfect."),
        ("W", "Wonderful. That room is one hundred and eighteen pounds per night."),
        ("M", "A hundred and eighteen a night, fine. Is breakfast included?"),
        ("W", "Yes, and breakfast is served from seven o'clock in the morning."),
        ("M", "From seven, good. Could you arrange anything for getting from the airport?"),
        ("W", "Of course — we can book an airport taxi to collect you."),
        ("M", "An airport taxi would be great. Can it come in the evening?"),
        ("W", "Certainly. What time shall I say?"),
        ("M", "Let's say half past six in the evening."),
        ("W", "Six thirty p.m., noted. Could I take an email for the confirmation?"),
        ("M", "Yes, it's collins, at northmail dot com. That's N-O-R-T-H-M-A-I-L."),
        ("W", "Northmail dot com, thank you. And just so you know, you can cancel free of charge up to twenty-four hours before arrival."),
        ("M", "Twenty-four hours before — that's good to know. Thanks very much."),
    ],
    (5, 2): [
        ("NARRATOR", "Section 2. You will hear the manager of a community centre describing the newly refurbished building. First, you have some time to look at questions 11 to 20."),
        ("W2", "Hello and welcome. I'm delighted to show you around our newly refurbished community centre. Do follow the plan in your handout."),
        ("W2", "As you come in, the desk on the bottom left, area A, is the Reception — that's where you sign in and pick up timetables."),
        ("W2", "Straight ahead at the top, the large room marked B is the Dance Studio, with its new sprung floor."),
        ("W2", "Next to it, in the top right, area C, is the Computer Room, with brand-new machines."),
        ("W2", "And out the back, bottom right, area E, is our Community Garden, which volunteers have completely replanted."),
        ("W2", "Now, some news. The centre officially reopens on Saturday with a free open day."),
        ("W2", "Every new member receives a free fitness session with one of our instructors to get started."),
        ("W2", "We've a new cafe too. To keep things simple at first, it will mainly sell snacks and drinks rather than full meals."),
        ("W2", "Evening classes run until late, but everything finishes by nine p.m., when the building closes."),
        ("W2", "We're also looking for help — in particular, we need volunteers for the gardening club on Sunday mornings."),
        ("W2", "And if you'd like to join any of the opening-day workshops, please book online beforehand, as spaces are limited."),
        ("W2", "Right — let me take you through to the studio first."),
    ],
    (5, 3): [
        ("NARRATOR", "Section 3. You will hear two students designing a transport survey with their tutor. First, you have some time to look at questions 21 to 30."),
        ("M2", "So, you're surveying how people travel into town. Let's review your decisions and the reasons behind them."),
        ("W", "First, we decided to interview people at bus stops."),
        ("M2", "And why there in particular?"),
        ("W", "Because it improves the response rate — people waiting for a bus are happy to chat."),
        ("M2", "Good reasoning — better response rate at bus stops. What about drivers?"),
        ("M", "We're leaving car drivers out of the main sample."),
        ("M2", "For what reason?"),
        ("M", "Mainly because it avoids disturbing drivers — we can't safely stop them while they're driving."),
        ("M2", "Sensible — it avoids disturbing the drivers. You also added a question on cycling?"),
        ("W", "Yes, we added a cycling question because it gives us a wider age range of respondents."),
        ("M2", "A wider age range — good. And the QR code?"),
        ("M", "We'll put a QR code on the card for follow-up comments, because it reduces printing costs."),
        ("M2", "Right, the QR code reduces printing. Now, your draft questionnaire — one issue stood out."),
        ("W", "What was that?"),
        ("M2", "Some of the questions are leading; they push people towards a particular answer. Reword those."),
        ("M", "Leading questions — we'll fix them. How big should the sample be?"),
        ("M2", "Aim for at least a hundred and twenty people to be reliable."),
        ("W", "A hundred and twenty, okay. We'll also compare weekday travel with weekend travel."),
        ("M2", "Weekday versus weekend — good idea. How will you present the results?"),
        ("M", "We thought maps would show the patterns best."),
        ("M2", "Maps work well here. Don't forget the paperwork — your ethics form must be signed by Monday."),
        ("W", "Signed by Monday, noted. And where should we test it first?"),
        ("M2", "Pilot the survey in the library foyer — it's busy and sheltered."),
        ("W", "The library foyer — perfect, thanks."),
    ],
    (5, 4): [
        ("NARRATOR", "Section 4. You will hear part of a lecture on volcanic soils and farming. First, you have some time to look at questions 31 to 40."),
        ("W2", "Today we look at why so many people farm on the slopes of dangerous volcanoes, and the balance of risk and reward involved."),
        ("W2", "Let's start with mineral content. Volcanic ash is packed with nutrients, so its effect on farming is high fertility — crops grow remarkably well."),
        ("W2", "The risk, though, is toxicity: some volcanic soils contain heavy metals that can build up to harmful levels."),
        ("W2", "Next, the porous structure of these soils. Because they're full of tiny holes, the effect is excellent drainage, so roots don't sit in water."),
        ("W2", "But that same porosity brings a risk of drought, as water can drain away too quickly in dry spells."),
        ("W2", "Then there are the steep slopes. Their effect on farming is to create varied microclimates, allowing different crops at different heights."),
        ("W2", "The obvious danger on steep ground is erosion, where heavy rain washes the soil away."),
        ("W2", "How does ash become soil in the first place? Largely through chemical weathering, as rain and air slowly break it down over decades."),
        ("W2", "These rich slopes are famous for certain crops — particularly coffee and grapes, which fetch high prices."),
        ("W2", "So what's the overall picture? Volcanic regions clearly combine opportunity and danger in equal measure."),
        ("W2", "The good news is that modern monitoring systems can give communities more time to evacuate before an eruption."),
        ("W2", "And so the central point of today's lecture is that successful volcanic farming depends on balancing fertile land with careful risk management."),
    ],
}
