"""IELTS replacement lemma pools used when curation removes basic words."""

from __future__ import annotations

# Per-topic spare lemmas (beginner / standard / advanced) — IELTS-relevant only.

REPLACEMENT_POOLS: dict[str, dict[str, list[str]]] = {
    "environment": {
        "beginner": [
            "emissions", "sustainable", "biodiversity", "renewable energy", "carbon footprint",
            "greenhouse gas", "deforestation", "conservation", "ecosystem", "pollution control",
            "climate action", "waste management", "air quality", "water scarcity", "recycling scheme",
            "environmental impact", "natural resource", "endangered species", "habitat loss",
            "global warming", "sea level rise", "clean energy", "environmental damage",
            "carbon neutral", "food chain", "urban sprawl", "environmental law", "net zero",
            "plastic waste", "organic farming", "protected species", "invasive species",
            "environmental policy", "eco-friendly", "carbon tax", "environmental justice",
            "sustainable farming", "water treatment", "noise pollution", "light pollution",
            "soil degradation", "ocean acidification", "coral bleaching", "wildfire",
            "carbon cycle", "land use", "biodegradable", "conservation area",
        ],
        "standard": [
            "mitigation strategy", "environmental governance", "planetary boundary",
            "green infrastructure", "circular economy", "sustainable development",
            "environmental justice", "climate resilience", "adaptive capacity",
            "carbon sequestration", "ecological footprint", "environmental remediation",
            "particulate matter", "volatile organic compound", "ecological niche",
            "carrying capacity", "trophic level", "biotic factor", "abiotic factor",
            "environmental degradation", "anthropogenic emissions", "climate adaptation",
            "environmental regulation", "ecosystem services", "environmental audit",
        ],
        "advanced": [
            "anthropogenic", "eutrophication", "bioaccumulation", "biomagnification",
            "phytoremediation", "rewilding", "afforestation", "ecocide",
            "xenobiotic", "endocrine disruptor", "atmospheric deposition",
            "thermohaline circulation", "albedo feedback", "methane clathrate",
            "environmental externalities", "precautionary principle", "intergenerational equity",
        ],
    },
    "health": {
        "beginner": [
            "public health", "life expectancy", "healthcare system", "preventive care",
            "chronic disease", "mental health", "physical activity", "balanced diet",
            "health insurance", "medical research", "clinical trial", "immune system",
            "antibiotic resistance", "organ transplant", "blood pressure", "health screening",
            "sedentary lifestyle", "calorie intake", "health inequality", "health policy",
            "pandemic preparedness", "health literacy", "rehabilitation", "outpatient care",
            "intensive care", "medical staff", "health outcome", "wellbeing",
            "substance abuse", "health promotion", "disease prevention", "healthcare access",
            "maternal health", "child mortality", "health expenditure", "primary care",
            "mental disorder", "health crisis", "vaccination programme", "health surveillance",
        ],
        "standard": [
            "epidemiological study", "public health intervention", "health disparities",
            "social determinants of health", "health equity", "universal healthcare",
            "pharmaceutical regulation", "clinical governance", "patient safety",
            "health technology assessment", "telemedicine", "personalised medicine",
            "comorbidity", "health economics", "population health", "health behaviour",
        ],
        "advanced": [
            "pathogenesis", "aetiology", "prognosis", "comorbidity", "iatrogenic",
            "pharmacokinetics", "pharmacodynamics", "epigenetics", "biomarker",
            "randomised controlled trial", "double-blind study", "placebo effect",
            "herd immunity", "antimicrobial stewardship", "palliative care",
            "psychosocial determinants", "health inequity", "social epidemiology",
        ],
    },
    "technology": {
        "beginner": [
            "digital literacy", "cybersecurity", "automation", "innovation", "connectivity",
            "broadband access", "data privacy", "online safety", "digital divide",
            "remote working", "video conferencing", "streaming service", "digital economy",
            "tech startup", "platform economy", "surveillance technology", "wearable tech",
            "smart device", "internet of things", "facial recognition", "e-commerce",
            "digital transformation", "tech regulation", "open source", "user interface",
            "data breach", "malware", "encryption", "digital footprint", "tech ethics",
            "artificial intelligence", "machine learning", "cloud computing", "big data",
            "social media", "digital skills", "tech industry", "electronic waste",
            "online security", "virtual meeting", "tech innovation", "digital tools",
        ],
        "standard": [
            "algorithmic transparency", "data governance", "platform accountability",
            "digital rights", "net neutrality", "content moderation", "deepfake",
            "predictive analytics", "natural language processing", "neural network",
            "autonomous vehicle", "smart city", "fintech", "healthtech", "edtech",
            "green tech", "intellectual property", "software development", "user experience",
            "two-factor authentication", "misinformation", "screen addiction", "tech giant",
        ],
        "advanced": [
            "algorithmic bias", "adversarial attack", "federated learning", "edge computing",
            "quantum computing", "nanotechnology", "biometric authentication",
            "zero-knowledge proof", "homomorphic encryption", "distributed ledger",
            "smart contract", "serverless computing", "penetration testing",
            "surveillance capitalism", "attention economy", "data sovereignty",
            "technological determinism", "algorithmic accountability", "digital colonialism",
        ],
    },
    "education": {
        "beginner": [
            "curriculum", "literacy", "numeracy", "scholarship", "enrolment",
            "tuition fees", "academic performance", "higher education", "vocational training",
            "distance learning", "blended learning", "e-learning", "inclusive education",
            "formative assessment", "summative assessment", "standardised test",
            "academic integrity", "plagiarism", "peer learning", "lifelong learning",
            "compulsory education", "student loan", "school dropout", "teacher training",
            "parental involvement", "extracurricular activity", "study abroad",
            "language barrier", "STEM education", "media literacy", "financial literacy",
            "digital skills", "employability", "education policy", "education reform",
            "critical thinking", "learning outcome", "classroom management",
            "special needs", "early childhood education", "adult education",
        ],
        "standard": [
            "pedagogical approach", "learning analytics", "competency-based education",
            "inquiry-based learning", "differentiated instruction", "assessment for learning",
            "educational attainment", "widening participation", "academic mobility",
            "internationalisation of education", "quality assurance", "accreditation",
            "educational measurement", "cognitive development", "metacognitive skills",
        ],
        "advanced": [
            "constructivism", "metacognition", "self-regulated learning", "scaffolding",
            "zone of proximal development", "threshold concept", "disciplinary literacy",
            "epistemic agency", "communities of practice", "situated learning",
            "critical pedagogy", "transformative learning", "decolonising curriculum",
            "academic discourse", "psychometrics", "educational governance",
        ],
    },
    "society": {
        "beginner": [
            "social inequality", "social mobility", "welfare state", "minimum wage",
            "gender pay gap", "racial discrimination", "social exclusion", "gentrification",
            "urbanisation", "ageing population", "immigration policy", "multiculturalism",
            "social cohesion", "civic engagement", "political polarisation", "globalisation",
            "income inequality", "wealth distribution", "social class", "meritocracy",
            "human rights", "freedom of speech", "press freedom", "censorship",
            "hate crime", "housing crisis", "homelessness", "prison reform",
            "restorative justice", "rule of law", "democratic values", "corruption",
            "social norm", "cultural values", "secularism", "civil society",
            "non-governmental organisation", "food bank", "child poverty", "drug abuse",
        ],
        "standard": [
            "social capital", "community development", "voter turnout", "populism",
            "nationalism", "upward mobility", "poverty trap", "social security",
            "unemployment benefit", "marginalisation", "rural decline", "birth rate decline",
            "integration", "assimilation", "fake news", "propaganda", "domestic violence",
            "gang culture", "knife crime", "rehabilitation", "capital punishment",
            "social contract", "bribery", "tax evasion", "whistleblowing", "taboo", "stigma",
        ],
        "advanced": [
            "stratification", "hegemony", "intersectionality", "structural violence",
            "institutional racism", "cultural imperialism", "postcolonialism",
            "neo-liberalism", "social constructionism", "critical race theory",
            "authoritarianism", "civil disobedience", "social movement", "collective action",
            "surveillance society", "commodification", "cultural homogenisation",
            "epistemic injustice", "post-truth", "risk society",
        ],
    },
    "travel": {
        "beginner": [
            "tourism industry", "sustainable tourism", "eco-tourism", "mass tourism",
            "business travel", "adventure travel", "cultural exchange", "heritage site",
            "world heritage", "national park", "guided tour", "travel insurance",
            "visa requirement", "border control", "culture shock", "local cuisine",
            "accommodation", "cruise", "road trip", "itinerary", "travel budget",
            "exchange rate", "tourist attraction", "peak season", "overtourism",
            "digital nomad", "gap year", "study abroad", "medical tourism",
            "travel restriction", "carbon footprint of travel", "airline emissions",
            "low-cost carrier", "high-speed rail", "public transport system",
            "tourist revenue", "local economy", "cultural preservation", "heritage tourism",
            "rural tourism", "backpacking", "package holiday",
        ],
        "standard": [
            "destination management", "tourism governance", "carrying capacity",
            "tourist saturation", "resident attitude", "staged authenticity",
            "place identity", "cross-cultural communication", "intercultural competence",
            "cultural diplomacy", "soft power", "global citizenship", "cosmopolitanism",
            "transport poverty", "aviation tax", "hub-and-spoke model", "transit hub",
            "intermodal transport", "transport emissions", "destination branding",
            "place marketing", "tourism multiplier effect", "leakage effect",
        ],
        "advanced": [
            "geotourism", "thanatourism", "voluntourism", "transformative travel",
            "slow travel", "tourist gaze", "heterotopia", "liminal space",
            "diaspora tourism", "mobility capital", "transnationalism",
            "open skies agreement", "last-mile connectivity", "carbon offsetting",
            "enclave tourism", "overtourism paradox", "post-pandemic travel",
            "tourism resilience", "commodification of culture",
        ],
    },
    "science": {
        "beginner": [
            "scientific method", "hypothesis", "empirical evidence", "peer review",
            "research methodology", "data analysis", "control group", "variable",
            "reproducibility", "laboratory experiment", "field study", "quantitative research",
            "qualitative research", "systematic review", "meta-analysis", "randomised trial",
            "sample size", "statistical significance", "correlation", "causation",
            "scientific consensus", "climate science", "evolutionary biology", "genetics",
            "neuroscience", "biochemistry", "organic chemistry", "nuclear energy",
            "space exploration", "gene editing", "stem cell", "vaccination science",
            "epidemiology", "mathematical modelling", "computer simulation",
            "nanotechnology", "materials science", "biotechnology", "environmental science",
            "ecology", "oceanography", "geology", "astronomy",
        ],
        "standard": [
            "observation", "scientific inquiry", "experimental design", "data collection",
            "statistical analysis", "research ethics", "informed consent",
            "double-blind study", "placebo control", "longitudinal study",
            "cross-sectional study", "case-control study", "cohort study",
            "genome sequencing", "protein synthesis", "cell division",
            "natural selection", "fossil record", "radioactive decay",
        ],
        "advanced": [
            "falsifiability", "paradigm shift", "reductionism", "emergentism",
            "quantum entanglement", "wave-particle duality", "dark matter", "dark energy",
            "entropy", "CRISPR-Cas9", "epigenetics", "proteomics", "genomics",
            "synthetic biology", "neuroplasticity", "precision medicine", "immunotherapy",
            "bioinformatics", "computational biology", "protein folding",
            "integrated information theory", "consciousness studies",
        ],
    },
    "business": {
        "beginner": [
            "revenue", "investment", "entrepreneur", "competition", "market share",
            "cash flow", "profit margin", "business model", "supply chain", "logistics",
            "human resources", "recruitment", "corporate culture", "merger", "acquisition",
            "startup ecosystem", "venture capital", "stock market", "dividend",
            "shareholder", "stakeholder", "corporate governance", "business strategy",
            "market research", "consumer behaviour", "brand identity", "digital marketing",
            "customer retention", "e-commerce", "outsourcing", "economies of scale",
            "return on investment", "working capital", "balance sheet", "income statement",
            "joint venture", "franchise", "IPO", "board of directors", "business intelligence",
            "customer acquisition", "loyalty programme", "subscription model",
        ],
        "standard": [
            "entrepreneurship", "revenue stream", "competitive advantage", "operations management",
            "talent management", "performance review", "organisational structure",
            "angel investor", "seed funding", "content marketing", "omnichannel",
            "price elasticity", "supply and demand", "offshoring", "nearshoring",
            "B2B", "B2C", "SaaS", "platform business", "data-driven decision", "KPI", "OKR",
        ],
        "advanced": [
            "disruptive innovation", "value chain analysis", "dynamic capabilities",
            "agency theory", "information asymmetry", "transaction cost economics",
            "stakeholder theory", "ESG investing", "impact investing", "triple bottom line",
            "corporate social responsibility", "brand equity", "customer lifetime value",
            "unit economics", "EBITDA", "discounted cash flow", "behavioural finance",
            "prospect theory", "game theory", "Nash equilibrium", "market microstructure",
        ],
    },
}

# Cross-topic AWL / linking fallbacks when a topic pool runs dry.
GLOBAL_REPLACEMENT_POOLS: dict[str, list[str]] = {
    "beginner": [
        "analyse", "approach", "area", "assess", "assume", "authority", "available",
        "benefit", "concept", "consistent", "constitutional", "context", "contract",
        "create", "data", "definition", "derived", "distribution", "economic",
        "environment", "established", "estimate", "evidence", "export", "factors",
        "financial", "formula", "function", "identified", "income", "indicate",
        "individual", "interpretation", "involved", "issues", "labour", "legal",
        "legislation", "major", "method", "occur", "percent", "period", "policy",
        "principle", "procedure", "process", "required", "research", "response",
        "role", "section", "sector", "significant", "similar", "source", "specific",
        "structure", "theory", "variables", "consequently", "furthermore", "whereas",
        "nevertheless", "provided that", "in contrast", "as a result", "on balance",
    ],
    "standard": [
        "fluctuate", "phenomenon", "hypothesis", "implication", "infrastructure",
        "mechanism", "paradigm", "predominantly", "presumably", "primarily",
        "radical", "rational", "recovery", "regime", "reinforce", "relevant",
        "residential", "resolve", "retain", "sequence", "series", "shift",
        "simultaneous", "sophisticated", "subsequent", "summary", "undertake",
        "validity", "voluntary", "whereby", "feasible", "detrimental", "viable alternative",
        "mitigate", "exacerbate", "allocate", "compensate", "comprise", "constrain",
        "contemporary", "controversy", "demonstrate", "diminish", "eliminate",
    ],
    "advanced": [
        "ameliorate", "anomaly", "antithesis", "axiomatic", "cacophony", "capitulate",
        "circumvent", "concomitant", "conundrum", "corroborate", "dichotomy",
        "disseminate", "ephemeral", "equanimity", "exacerbation", "extrapolate",
        "hegemonic", "idiosyncratic", "inexorable", "juxtaposition", "lacuna",
        "obfuscate", "paradigmatic", "pernicious", "precarious", "proliferate",
        "recalcitrant", "salient", "substantiate", "tenuous", "ubiquitous",
        "unequivocal", "vicarious", "vociferous", "zeitgeist", "anachronistic",
        "bellicose", "capricious", "deleterious", "efficacious", "fastidious",
    ],
}
