# Generated by Django 4.2.11 on 2026-04-16 05:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=100)),
                ('topic', models.CharField(choices=[('environment', 'Environment'), ('health', 'Health'), ('technology', 'Technology'), ('education', 'Education'), ('society', 'Society'), ('travel', 'Travel'), ('science', 'Science'), ('business', 'Business')], max_length=50)),
                ('level', models.IntegerField(choices=[(1, 'Beginner'), (2, 'Standard'), (3, 'Advanced')], default=1)),
                ('definition', models.TextField()),
                ('example_sentence', models.TextField()),
                ('collocations', models.JSONField(blank=True, default=list)),
                ('part_of_speech', models.CharField(blank=True, max_length=50)),
                ('phonetic', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'ordering': ['topic', 'level', 'word'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(choices=[(1, 'Beginner'), (2, 'Standard'), (3, 'Advanced')], default=1)),
                ('placement_score', models.IntegerField(default=0)),
                ('placement_completed', models.BooleanField(default=False)),
                ('streak', models.IntegerField(default=0)),
                ('best_streak', models.IntegerField(default=0)),
                ('reading_speed_wpm', models.IntegerField(blank=True, null=True)),
                ('review_easy_days', models.IntegerField(default=7)),
                ('review_hard_days', models.IntegerField(default=1)),
                ('last_activity_date', models.DateField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TypeItResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_text', models.TextField()),
                ('mode', models.CharField(default='word', max_length=50)),
                ('band_score', models.FloatField(blank=True, null=True)),
                ('improved_text', models.TextField(blank=True)),
                ('ielts_mode', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('word', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vocabulary.word')),
            ],
        ),
        migrations.CreateModel(
            name='CustomDeck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CustomCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=200)),
                ('definition', models.TextField()),
                ('example_sentence', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vocabulary.customdeck')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VocabularyProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(default='flashcard', max_length=50)),
                ('status', models.CharField(default='learning', max_length=20)),
                ('times_correct', models.IntegerField(default=0)),
                ('times_wrong', models.IntegerField(default=0)),
                ('mastery_level', models.IntegerField(default=1)),
                ('next_review', models.DateTimeField(blank=True, null=True)),
                ('last_reviewed', models.DateTimeField(blank=True, null=True)),
                ('is_favored', models.BooleanField(default=False)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vocabulary.word')),
            ],
            options={
                'unique_together': {('student', 'word')},
            },
        ),
    ]
