# Generated by Django 5.2.12 on 2026-04-03 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=255, unique=True)),
                ('topic', models.CharField(choices=[('environment', 'Environment'), ('health', 'Health'), ('technology', 'Technology'), ('education', 'Education'), ('society', 'Society')], max_length=32)),
                ('level', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3')])),
                ('definition', models.TextField(blank=True)),
                ('example_sentence', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['topic', 'level', 'word'],
            },
        ),
    ]
