# Generated by Django 5.2.12 on 2026-04-04 05:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocabulary', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=255)),
                ('definition', models.TextField(blank=True)),
                ('example_sentence', models.TextField(blank=True)),
                ('topic', models.CharField(choices=[('environment', 'Environment'), ('health', 'Health'), ('technology', 'Technology'), ('education', 'Education'), ('society', 'Society'), ('other', 'Other')], max_length=32)),
                ('level', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3')])),
                ('is_mastered', models.BooleanField(default=False)),
                ('review_count', models.PositiveIntegerField(default=0)),
                ('next_review_at', models.DateTimeField(blank=True, help_text='Due for spaced-repetition review when <= now (null = due now).', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_cards', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['topic', 'level', 'word'],
                'constraints': [models.UniqueConstraint(fields=('student', 'word', 'topic'), name='vocabulary_unique_custom_word_per_topic')],
            },
        ),
    ]
