# Generated by Django 4.2.11 on 2026-04-17 22:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vocabulary', '0002_populate_initial_vocab'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='vocabularyprogress',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='customcard',
            name='definition_image',
            field=models.ImageField(blank=True, null=True, upload_to='vocab_custom_images/'),
        ),
        migrations.AddField(
            model_name='customcard',
            name='is_mastered',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customcard',
            name='level',
            field=models.IntegerField(choices=[(1, 'Beginner'), (2, 'Standard'), (3, 'Advanced')], default=1),
        ),
        migrations.AddField(
            model_name='customcard',
            name='next_review_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customcard',
            name='part_of_speech',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='customcard',
            name='topic',
            field=models.CharField(choices=[('environment', 'Environment'), ('health', 'Health'), ('technology', 'Technology'), ('education', 'Education'), ('society', 'Society'), ('travel', 'Travel'), ('science', 'Science'), ('business', 'Business'), ('other', 'My vocabulary')], default='other', max_length=50),
        ),
        migrations.AddField(
            model_name='vocabularyprogress',
            name='custom_card',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='progress_rows', to='vocabulary.customcard'),
        ),
        migrations.AddField(
            model_name='vocabularyprogress',
            name='last_session_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vocabularyprogress',
            name='sessions_seen',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='vocabularyprogress',
            name='times_marked_hard',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='vocabularyprogress',
            name='times_seen',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='vocabularyprogress',
            name='type_success_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='word',
            name='definition_image',
            field=models.ImageField(blank=True, null=True, upload_to='vocab_word_images/'),
        ),
        migrations.AlterField(
            model_name='vocabularyprogress',
            name='word',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='progress_rows', to='vocabulary.word'),
        ),
        migrations.AddConstraint(
            model_name='vocabularyprogress',
            constraint=models.UniqueConstraint(condition=models.Q(('word__isnull', False)), fields=('student', 'word'), name='vocab_progress_student_word_uniq'),
        ),
        migrations.AddConstraint(
            model_name='vocabularyprogress',
            constraint=models.UniqueConstraint(condition=models.Q(('custom_card__isnull', False)), fields=('student', 'custom_card'), name='vocab_progress_student_custom_uniq'),
        ),
    ]
