# Generated by Django 5.2.12 on 2026-04-05 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocabulary', '0002_customcard'),
    ]

    operations = [
        migrations.AddField(
            model_name='customcard',
            name='definition_image',
            field=models.ImageField(blank=True, help_text='Optional picture shown on the definition side when you study this card.', null=True, upload_to='vocab/custom/'),
        ),
        migrations.AddField(
            model_name='word',
            name='definition_image',
            field=models.ImageField(blank=True, help_text='Optional picture shown on the definition side of flashcards.', null=True, upload_to='vocab/words/'),
        ),
    ]
