# Generated by Django 4.2.11 on 2026-04-17 23:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vocabulary', '0003_sync_schema'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopicIELTSWordCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(db_index=True, max_length=50, unique=True)),
                ('status', models.CharField(default='generating', max_length=20)),
                ('beginner', models.JSONField(blank=True, default=list)),
                ('standard', models.JSONField(blank=True, default=list)),
                ('advanced', models.JSONField(blank=True, default=list)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='vocabularyprogress',
            name='easy_chip_master_count',
            field=models.IntegerField(default=0, help_text='Times user rated Easy on flashcards; chip turns green at 3.'),
        ),
        migrations.AddField(
            model_name='word',
            name='topic_pack',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pack_words', to='vocabulary.topicieltswordcache'),
        ),
    ]
