# Generated by Django 5.2.12 on 2026-04-05 22:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocabulary', '0003_definition_images'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VocabFavorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('custom_card', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='vocabulary.customcard')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vocab_favorites', to=settings.AUTH_USER_MODEL)),
                ('word', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='vocabulary.word')),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('custom_card__isnull', True), ('word__isnull', False)), models.Q(('custom_card__isnull', False), ('word__isnull', True)), _connector='OR'), name='vocab_favorite_exactly_one_target'), models.UniqueConstraint(condition=models.Q(('word__isnull', False)), fields=('user', 'word'), name='uniq_vocab_fav_user_word'), models.UniqueConstraint(condition=models.Q(('custom_card__isnull', False)), fields=('user', 'custom_card'), name='uniq_vocab_fav_user_custom')],
            },
        ),
    ]
