# Generated by Django 4.2.11 on 2026-04-19 20:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vocabulary', '0004_topic_ielts_ai_and_word_pack'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='ielts_note',
            field=models.TextField(blank=True, help_text='IELTS usage note for Type it and study views.'),
        ),
        migrations.CreateModel(
            name='TypeItAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deck_slug', models.CharField(db_index=True, max_length=80)),
                ('definition_score', models.PositiveSmallIntegerField()),
                ('sentence_score', models.PositiveSmallIntegerField()),
                ('total_score', models.PositiveSmallIntegerField()),
                ('assisted', models.BooleanField(default=False)),
                ('student_definition', models.TextField(blank=True)),
                ('student_sentence', models.TextField(blank=True)),
                ('feedback_json', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='type_it_attempts', to=settings.AUTH_USER_MODEL)),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='type_it_attempts', to='vocabulary.word')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['student', 'word'], name='vocabulary__student_6076a5_idx'), models.Index(fields=['student', 'deck_slug'], name='vocabulary__student_5a243b_idx')],
            },
        ),
    ]
