# Generated by Django 5.2.12 on 2026-04-05 22:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocabulary', '0004_vocab_favorite'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VocabularyProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('times_seen', models.PositiveIntegerField(default=0)),
                ('times_correct', models.PositiveIntegerField(default=0)),
                ('times_wrong', models.PositiveIntegerField(default=0)),
                ('times_marked_hard', models.PositiveIntegerField(default=0)),
                ('sessions_seen', models.PositiveIntegerField(default=0)),
                ('last_session_date', models.DateField(blank=True, null=True)),
                ('mastery_level', models.PositiveSmallIntegerField(default=1)),
                ('next_review', models.DateTimeField(blank=True, null=True)),
                ('last_reviewed', models.DateTimeField(blank=True, null=True)),
                ('type_success_count', models.PositiveIntegerField(default=0, help_text='Successful Type-it (example mode) checks; used for mastery level 4.')),
                ('custom_card', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_progress', to='vocabulary.customcard')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vocabulary_progress', to=settings.AUTH_USER_MODEL)),
                ('word', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_progress', to='vocabulary.word')),
            ],
            options={
                'ordering': ['-last_reviewed', '-pk'],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('custom_card__isnull', True), ('word__isnull', False)), models.Q(('custom_card__isnull', False), ('word__isnull', True)), _connector='OR'), name='vocab_progress_exactly_one_target'), models.UniqueConstraint(condition=models.Q(('word__isnull', False)), fields=('student', 'word'), name='uniq_vocab_progress_student_word'), models.UniqueConstraint(condition=models.Q(('custom_card__isnull', False)), fields=('student', 'custom_card'), name='uniq_vocab_progress_student_custom')],
            },
        ),
    ]
