# Generated by Django 4.2.11 on 2026-04-19 20:20

from django.db import migrations


def seed_environment_beginner_words(apps, schema_editor):
    Word = apps.get_model("vocabulary", "Word")
    from vocabulary.type_it_enrichment import MANUAL

    for (t, lv, lw), data in MANUAL.items():
        if t != "environment" or lv != 1:
            continue
        found = None
        for row in Word.objects.filter(topic=t, level=lv):
            if row.word.lower() == lw:
                found = row
                break
        payload = {
            "definition": data["definition"],
            "example_sentence": data["example"],
            "collocations": data["collocations"],
            "part_of_speech": data["pos"],
            "ielts_note": data["ielts_note"],
        }
        if found:
            for k, v in payload.items():
                setattr(found, k, v)
            found.save()
        else:
            Word.objects.create(
                word=lw,
                topic=t,
                level=lv,
                **payload,
            )


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("vocabulary", "0005_word_ielts_note_typeit_attempt"),
    ]

    operations = [
        migrations.RunPython(seed_environment_beginner_words, noop_reverse),
    ]
