# Generated by Django 5.2.12 on 2026-04-07 20:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocabulary', '0005_vocabulary_progress'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='customcard',
            name='topic',
            field=models.CharField(choices=[('environment', 'Environment'), ('health', 'Health'), ('technology', 'Technology'), ('education', 'Education'), ('society', 'Society'), ('other', 'Select vocabulary')], max_length=32),
        ),
        migrations.CreateModel(
            name='CustomCardSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_card_sets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='customcard',
            name='card_set',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cards', to='vocabulary.customcardset'),
        ),
        migrations.AddConstraint(
            model_name='customcardset',
            constraint=models.UniqueConstraint(fields=('student', 'name'), name='vocab_unique_custom_card_set_name_per_student'),
        ),
    ]
