# Generated by Django 5.2.12 on 2026-04-07 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocabulary', '0006_custom_card_set'),
    ]

    operations = [
        migrations.AddField(
            model_name='customcardset',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
