# Generated by Django 4.2.11 on 2026-04-20 07:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vocabulary', '0006_seed_type_it_environment_words'),
    ]

    operations = [
        migrations.AddField(
            model_name='customdeck',
            name='colour',
            field=models.CharField(default='navy', max_length=20),
        ),
        migrations.AddField(
            model_name='customdeck',
            name='emoji',
            field=models.CharField(default='📖', max_length=10),
        ),
        migrations.AlterField(
            model_name='typeitattempt',
            name='word',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='type_it_attempts', to='vocabulary.word'),
        ),
        migrations.CreateModel(
            name='CustomDeckWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='words', to='vocabulary.customdeck')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='typeitattempt',
            name='custom_word',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='type_it_attempts', to='vocabulary.customdeckword'),
        ),
    ]
