# Generated by Django 5.2.12 on 2026-04-07 20:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vocabulary", "0007_custom_card_set_description"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(old_name="CustomCardSet", new_name="CustomDeck"),
        migrations.RenameField(
            model_name="customcard",
            old_name="card_set",
            new_name="deck",
        ),
        migrations.AlterField(
            model_name="customdeck",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="custom_decks",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.RemoveConstraint(
            model_name="customdeck",
            name="vocab_unique_custom_card_set_name_per_student",
        ),
        migrations.AddConstraint(
            model_name="customdeck",
            constraint=models.UniqueConstraint(
                fields=("student", "name"),
                name="vocab_unique_custom_deck_name_per_student",
            ),
        ),
    ]
