# Generated by Django 5.2.12 on 2026-07-16 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vocabulary', '0018_feedback_submission'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feedbacksubmission',
            options={'ordering': ['-created_at'], 'verbose_name': 'Feedback submission', 'verbose_name_plural': 'Feedback submissions'},
        ),
    ]
