# Generated by Django 5.2.12 on 2026-07-16 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocabulary', '0019_feedback_verbose_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedbacksubmission',
            name='page_url',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
