# Generated by Django 4.2.11 on 2026-07-18 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocabulary', '0021_signupcode'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maintenance_mode', models.BooleanField(default=False, help_text='When on, visitors see the maintenance page (staff and admin are exempt).')),
                ('maintenance_message', models.TextField(default="We're making some improvements. BoostingScore will be back shortly.", help_text='Shown on the maintenance page.')),
            ],
            options={
                'verbose_name': 'Site settings',
                'verbose_name_plural': 'Site settings',
            },
        ),
    ]
